Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8742090705095711985) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5718090?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[436/888] ACTION //front_end/testing:testing(//build/toolchain/linux:x64)
FAILED: gen/front_end/testing/testing-tsconfig.json gen/front_end/testing/ConsoleHelpers.js gen/fron...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/testing/testing-tsconfig.json

../../front_end/testing/MockScopeChain.ts(214,44): error TS2345: Argument of type 'DebuggerModel' is not assignable to parameter of type 'DebuggerPausedDetails'.
Type 'DebuggerModel' is missing the following properties from type 'DebuggerPausedDetails': debuggerModel, reason, auxData, breakpointIds, and 4 more.


```
#### [Click here for more information](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8742090705095711985/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 1
Tag: autogenerated:cq:dry-run:1721289637
Attention: {"person_ident":"Gerrit User 1323977 \u003c1323977@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}