Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8835950327150878945
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [841/1962] ACTION //front_end/ui/legacy:ui-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/ui/legacy/ui-tsconfig.json gen/front_end/ui/legacy/ARIAUtils.js gen/front_end/...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/legac...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/ui/legacy/ui-tsconfig.json
    
    ../../front_end/ui/legacy/FilterBar.ts(104,12): error TS2339: Property 'addEventListener' does not exist on type 'FilterUI'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cv