Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8775199301971090273) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[2512/3967] ACTION //front_end/models/persistence:persistence-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/persistence/persistence-tsconfig.json gen/front_end/models/persistence/...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/p...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/persistence/persistence-tsconfig.json

error TS5055: Cannot write file '/b/s/w/ir/cache/builder/devtools-frontend/front_end/models/javascript_metadata/NativeFunctions.js' because it would overwrite input file.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run:1689714345
Attention: {"person_ident":"Gerrit User 1429955 \u003c1429955@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}