Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8851362269291357088
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [529/1581] ACTION //front_end/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/ChildTargetManager.ts(104,18): error TS2339: Property '_targetId' does not exist on type 'TargetCrashedEvent'.
    ../../front_end/sdk/ChildTargetManager.ts(104,29): error TS2339: Property '_status' does not exist on type 'TargetCrashedEvent'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run