Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_win64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8866179908015590512
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [155/325] ACTION //front_end/network:network-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/network/network-tsconfig.json gen/front_end/network/network-tsconfig.json.tsbu...(too long)
    C:/b/s/w/ir/cipd_bin_packages/python.exe ../../third_party/typescript/ts_library.py --tsconfig_outpu...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/network/network-tsconfig.json
    
    ../../front_end/network/NetworkLogView.js(1127,75): error TS2339: Property 'flatChildren' does not exist on type 'DataGridNode<ViewportDataGridNode<SortableDataGridNode<NetworkNode>>>'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_win64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8866179656635402416
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [155/325] ACTION //front_end/network:network-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/network/network-tsconfig.json gen/front_end/network/network-tsconfig.json.tsbu...(too long)
    C:/b/s/w/ir/cipd_bin_packages/python.exe ../../third_party/typescript/ts_library.py --tsconfig_outpu...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/network/network-tsconfig.json
    
    ../../front_end/network/NetworkLogView.js(1127,75): error TS2339: Property 'flatChildren' does not exist on type 'DataGridNode<ViewportDataGridNode<SortableDataGridNode<NetworkNode>>>'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run