Revert "[search] Remove 'columnNumber' from SearchMatch"
This reverts commit 8da0790f936edca4e5962dc56e94e9e42a81405f.

Reason for revert:
TypeScript compilation failed:

```
TypeScript compilation failed. Used tsconfig gen/front_end/panels/sources/sources-tsconfig.json

../../front_end/panels/sources/SourcesSearchScope.ts(310,65): error TS2339: Property 'columnNumber' does not exist on type 'SearchMatch'.
```

Presumably, the original CL depends on the reverted CL [1].
We'll tentatively revert it because the revert CL [2] for [1] landed.

[1] https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4797648
[2] https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4797745

Original change's description:
> [search] Remove 'columnNumber' from SearchMatch
>
> Small cleanup. The `SearchMatchExact` class now has the columnNumber
> and matchLength, so we no longer need it on `SearchMatch`.
>
> R=jarin@chromium.org
>
> Bug: 1468875
> Change-Id: Idd1c6f69d3f303ef8a20b12be8affe67ecf43bd3
> Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4798129
> Reviewed-by: Jaroslav Sevcik <jarin@chromium.org>
> Commit-Queue: Jaroslav Sevcik <jarin@chromium.org>
> Commit-Queue: Simon Zünd <szuend@chromium.org>
> Auto-Submit: Simon Zünd <szuend@chromium.org>

Bug: 1468875
Change-Id: I6fb1590cde9365020d9d5178ef3afc4ca8ad878e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true