Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8745326040254048913) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5626313?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1189/2271] ACTION //front_end/panels/timeline/components:components(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/components/components-tsconfig.json gen/front_end/panels/timel...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/components/components-tsconfig.json

../../front_end/panels/timeline/components/TimeRangeOverlay.ts(139,70): error TS2339: Property 'formatMicrosecondsTime' does not exist on type 'typeof import("/b/s/w/ir/cache/builder/devtools-frontend/out/Debug/gen/front_end/models/trace/helpers/Timing")'.


```
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8745326040254048913/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 1
Tag: autogenerated:cq:dry-run:1718204180
Attention: {"person_ident":"Gerrit User 1396442 \u003c1396442@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}