Update patch set 5
Patch Set 5:

Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8830319559486664401
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [4/2232] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    error TS5055: Cannot write file '/b/s/w/ir/cache/builder/devtools-frontend/front_end/models/javascript_metadata/NativeFunctions.js' because it would overwrite input file.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8830319455261544337
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1/2229] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    error TS5055: Cannot write file '/b/s/w/ir/cache/builder/devtools-frontend/front_end/models/javascript_metadata/NativeFunctions.js' because it would overwrite input file.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 5
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1365394 \u003c1365394@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#5: CQ full run failed."}