Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8784719591939934129) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[337/2663] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/CSSRule.ts(115,37): error TS2339: Property 'nestingSelectors' does not exist on type 'CSSRule'.
../../front_end/core/sdk/PreloadingModel.ts(226,28): error TS2339: Property 'key' does not exist on type 'PrefetchStatusUpdatedEvent'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run:1680635487
Attention: {"person_ident":"Gerrit User 1552582 \u003c1552582@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}