Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Failed Tryjobs:
* [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8757270413562643265). Summary [(view all results)](https://chromium-review.googlesource.com/c/5259698?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[741/2179] ACTION //front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/ServiceWorkerCacheModel.ts(29,14): error TS2420: Class 'ServiceWorkerCacheModel' incorrectly implements interface 'StorageDispatcher'.
Property 'interestGroupAuctionNetworkRequestCreated' is missing in type 'ServiceWorkerCacheModel' but required in type 'StorageDispatcher'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

---
* [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8757270413562643185). Summary [(view all results)](https://chromium-review.googlesource.com/c/5259698?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[76/2326] ACTION //front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/ServiceWorkerCacheModel.ts(29,14): error TS2420: Class 'ServiceWorkerCacheModel' incorrectly implements interface 'StorageDispatcher'.
Property 'interestGroupAuctionNetworkRequestCreated' is missing in type 'ServiceWorkerCacheModel' but required in type 'StorageDispatcher'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

---

Patch-set: 1
Tag: autogenerated:cq:dry-run:1706813025
Attention: {"person_ident":"Gerrit User 1434270 \u003c1434270@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}