Update patch set 6
Patch Set 6:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8743408391232612897) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5673433?checksPatchset=6&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1271/1536] ACTION //front_end/panels/timeline/components:unittests(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/components/unittests-tsconfig.json gen/front_end/panels/timeli...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/components/unittests-tsconfig.json

../../front_end/panels/timeline/components/CPUThrottlingSelector.test.ts(30,37): error TS2339: Property 'value' does not exist on type 'Element'.
```
##### ...The message was too long...
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8743408391232612897/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 6
Tag: autogenerated:cq:dry-run:1720032762
Attention: {"person_ident":"Gerrit User 1534302 \u003c1534302@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: Tryjobs failed"}