Let Karma fail if generated test file does not exist
$ npm run unittest

> chrome-devtools-frontend@ unittest /devtools-frontend
> python scripts/test/run_unittests.py --no-text-coverage

Using Chromium binary (/devtools-frontend/third_party/chrome/chrome-mac/Chromium.app/Contents/MacOS/Chromium)

Using karma config /devtools-frontend/out/Default/gen/test/unittests/front_end/karma.conf.js
30 04 2020 15:48:55.262:ERROR [config]: Error in config file!
  Error: Test file /devtools-frontend/test/unittests/front_end/common/Lazy_test.ts is not included in a BUILD.gn and therefore will not be run.
    at /devtools-frontend/out/Default/gen/test/unittests/front_end/karma.conf.js:37:11
    at Array.map (<anonymous>)
    at Object.<anonymous> (/devtools-frontend/out/Default/gen/test/unittests/front_end/karma.conf.js:32:44)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.parseConfig (/devtools-frontend/node_modules/karma/lib/config.js:358:22)

R=jacktfranklin@chromium.org
CC=sigurds@chromium.org

Bug: 1061125
Change-Id: I82a52d9de8d01e623ba5542ad922cc579dcbc72a