Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8791011161101916561) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[39/2261] ACTION //front_end/models/bindings:bindings-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/bindings/bindings-tsconfig.json gen/front_end/models/bindings/Breakpoin...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/b...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/bindings/bindings-tsconfig.json

../../front_end/models/bindings/BreakpointManager.ts(728,12): error TS2352: Conversion of type 'UserCondition' to type 'BackendCondition' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run:1674635325
Attention: {"person_ident":"Gerrit User 1323977 \u003c1323977@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}