Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8756931502142962801) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/5268881?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1644/2387] ACTION //test/e2e/console:console(//build/toolchain/linux:x64)
FAILED: gen/test/e2e/console/console-tsconfig.json gen/test/e2e/console/alert-toString-exception_tes...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/test/e2e/console/console-tsconfig.json

../../test/e2e/console/console-insight_test.ts(154,55): error TS2693: 'Console' only refers to a type, but is being used as a value here.
../../test/e2e/console/console-insight_test.ts(161,35): error TS2693: 'Console' only refers to a type, but is being used as a value here.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1707136352
Attention: {"person_ident":"Gerrit User 1410814 \u003c1410814@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}