Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8787114694015377873) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[919/2184] ACTION //front_end/models/bindings:bindings-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/bindings/bindings-tsconfig.json gen/front_end/models/bindings/Breakpoin...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/b...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/bindings/bindings-tsconfig.json

../../front_end/models/bindings/CompilerScriptMapping.ts(275,47): error TS2551: Property 'reverseMapTextRanges' does not exist on type 'SourceMap'. Did you mean 'reverseMapTextRange'?


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:full-run:1678351419
Attention: {"person_ident":"Gerrit User 1323977 \u003c1323977@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}