Update patch set 12
Patch Set 12:

I see a build error after this change rolled into Chromium at https://crrev.com/c/2008257.  I tried to revert using the Gerrit frontend but got a merge conflict and don't have cycles to continue.  Can you PTAL as soon as possible?

FAILED: gen/third_party/devtools-frontend/src/front_end/common/trie-tsconfig.json gen/third_party/devtools-frontend/src/front_end/common/Trie.js
python ../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py --tsconfig_output_location gen/third_party/devtools-frontend/src/front_end/common/trie-tscon
fig.json --sources ../../third_party/devtools-frontend/src/front_end/common/Trie.js

TypeScript compilation failed. Used tsconfig /usr/local/google/home/cmp/co/chromium/src/out/Release/gen/third_party/devtools-frontend/src/front_end/common/trie-tsconfig.json

../../../../../node_modules/@types/uglify-js/index.d.ts(9,30): error TS2307: Cannot find module 'source-map'.
../../../../../node_modules/@types/request/index.d.ts(15,27): error TS2307: Cannot find module 'form-data'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/objects/choice.d.ts(1,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/objects/separator.d.ts(1,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/objects/choices.d.ts(1,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/base.d.ts(2,28): error TS2307: Cannot find module 'rxjs'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/base.d.ts(3,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/checkbox.d.ts(1,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/confirm.d.ts(2,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/editor.d.ts(2,39): error TS2307: Cannot find module 'rxjs'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/editor.d.ts(3,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/expand.d.ts(3,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/input.d.ts(2,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/list.d.ts(2,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/number.d.ts(2,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/password.d.ts(2,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/prompts/rawlist.d.ts(1,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/ui/baseUI.d.ts(2,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/ui/bottom-bar.d.ts(2,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/ui/prompt.d.ts(1,35): error TS2307: Cannot find module 'rxjs'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/ui/prompt.d.ts(2,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/utils/events.d.ts(2,28): error TS2307: Cannot find module 'rxjs'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/utils/utils.d.ts(1,27): error TS2307: Cannot find module '../..'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/lib/utils/utils.d.ts(2,28): error TS2307: Cannot find module 'rxjs'.
../../../../../node_modules/@types/yeoman-generator/node_modules/@types/inquirer/index.d.ts(17,28): error TS2307: Cannot find module 'rxjs'.

Patch-set: 12
CC: Gerrit User 1000137 <1000137@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>