Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Jack, if I try to add 
>     @implements {FrameAssociated}
> annotations to Script or CSSStyleSheetHeaders, typescript complains that 
> gen/front_end/sdk/CSSStyleSheetHeader.d.ts(7,88): error TS2749: 'CSSStyleSheetHeader_base' refers to a value, but is being used as a type here. Did you mean 'typeof CSSStyleSheetHeader_base'?
> gen/front_end/sdk/Script.d.ts(7,75): error TS2749: 'Script_base' refers to a value, but is being used as a type here. Did you mean 'typeof Script_base'?
> 
> Do you know how to work around this?

Per the team chat: we think this is because of the upstream TypeScript compiler bug that has been fixed. I will look into upgrading TypeScript and see if that would fix the issue.

Patch-set: 1