Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8781398650917811713) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[4/595] ACTION //front_end/panels/timeline:timeline-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/timeline-tsconfig.json gen/front_end/panels/timeline/AppenderU...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/timeline-tsconfig.json

../../front_end/panels/timeline/GPUTrackAppender.ts(38,10): error TS2339: Property '#legacyEntryTypeByLevel' does not exist on type 'GPUTrackAppender'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run:1683802662
Attention: {"person_ident":"Gerrit User 1327793 \u003c1327793@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}