Update patch set 19
Patch Set 19:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8747121655542072945) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5551153?checksPatchset=19&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[902/2243] ACTION //front_end/models/issues_manager:issues_manager(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json

../../front_end/models/issues_manager/CookieDeprecationMetadataIssue.ts(28,110): error TS2339: Property 'operation' does not exist on type 'CookieDeprecationMetadataIssueDetails'.
```
##### ...The message was too long...
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8747121655542072945/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 19
Tag: autogenerated:cq:dry-run:1716491748
Attention: {"person_ident":"Gerrit User 1579342 \u003c1579342@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#19: Tryjobs failed"}