Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8778755978056970625) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[14/957] ACTION //front_end/models/issues_manager:issues_manager-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json

error TS6053: File '/b/s/w/ir/cache/builder/devtools-frontend/front_end/models/issues_manager/NavigatorUserAgentIssue.ts' not found.
The file is in the program because:
Part of 'files' list in tsconfig.json
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1686322912
Attention: {"person_ident":"Gerrit User 1525409 \u003c1525409@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}