Update patch set 10
Patch Set 10:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8753582159825194161) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5335660?checksPatchset=10&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[491/1113] ACTION //front_end/panels/timeline:timeline(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/timeline-tsconfig.json gen/front_end/panels/timeline/ActiveFil...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/timeline-tsconfig.json

../../front_end/panels/timeline/TimelineFlameChartDataProvider.ts(1360,43): error TS2339: Property 'revealEntry' does not exist on type 'CompatibilityTracksAppender'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 10
Tag: autogenerated:cq:dry-run:1710330396
Attention: {"person_ident":"Gerrit User 1593257 \u003c1593257@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#10: Tryjobs failed"}