Add sourcemap support to ts_library
This will result in nicer assertion messages with Karma.

Before:

HeadlessChrome 82.0.4071 (Mac OS X 10.15.3) Color defaults RGBA value to 0 if the RGBA initializing value given was negative FAILED
	AssertionError: RGBA array was not set correctly: expected [ 0, 0.5, 0.5, 0.5 ] to deeply equal [ 0, 0.5, 0.5, 0.6 ]
	    at Context.<anonymous> (test/unittests/front_end/common/Color_test.js:15:16)

After:

HeadlessChrome 82.0.4071 (Mac OS X 10.15.3) Color defaults RGBA value to 0 if the RGBA initializing value given was negative FAILED
	AssertionError: RGBA array was not set correctly: expected [ 0, 0.5, 0.5, 0.5 ] to deeply equal [ 0, 0.5, 0.5, 0.7 ]
	    at Context.<anonymous> (test/unittests/front_end/common/Color_test.ts:19:12 <- out/Default/gen/test/unittests/front_end/common/Color_test.js:15:16)

R=aerotwist@chromium.org,jacktfranklin@chromium.org
DISABLE_THIRD_PARTY_CHECK=Update to TypeScript

Bug: 1061125
Change-Id: Ia689b2a0a6e6f7d221d29786727700be02e8649b