Update patch set 6
Patch Set 6:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8751191014123453665) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5434063?checksPatchset=6&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[250/498] ACTION //front_end/panels/timeline:unittests(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/unittests-tsconfig.json gen/front_end/panels/timeline/Breadcru...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/unittests-tsconfig.json

../../front_end/panels/timeline/TimelineHistoryManager.test.ts(32,11): error TS2741: Property 'fileMetadata' is missing in type '{ legacyModel: Timeline.PerformanceModel.PerformanceModel; traceParseDataIndex: number; }' but required in type 'RecordingData'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 6
Tag: autogenerated:cq:dry-run:1712610653
Attention: {"person_ident":"Gerrit User 1593257 \u003c1593257@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: Tryjobs failed"}