Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8839739613832206400
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1487/1881] ACTION //test/unittests/front_end/core/sdk:sdk(//build/toolchain/linux:x64)
    FAILED: gen/test/unittests/front_end/core/sdk/sdk-tsconfig.json gen/test/unittests/front_end/core/sd...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/unittests/fro...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/test/unittests/front_end/core/sdk/sdk-tsconfig.json
    
    ../../test/unittests/front_end/core/sdk/CSSProperty_test.ts(17,37): error TS2339: Property '_formatStyle' does not exist on type 'typeof CSSProperty'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cv