Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8747173046706712385) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5548295?checksPatchset=3&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[4/534] ACTION //front_end/panels/network:network(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/network/network-tsconfig.json gen/front_end/panels/network/BinaryResour...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/n...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/network/network-tsconfig.json

../../front_end/panels/network/RequestTimingView.ts(364,18): error TS2339: Property 'workerRouterEvaluationStart' does not exist on type 'ResourceTiming'.
```
##### ...The message was too long...
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8747173046706712385/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 3
Tag: autogenerated:cq:dry-run:1716442657
Attention: {"person_ident":"Gerrit User 3362409 \u003c3362409@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}