Update patch set 9
Patch Set 9:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8738273935692764865) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5823431?checksPatchset=9&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[168/1088] ACTION //front_end/panels/application/components:components(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/application/components/components-tsconfig.json gen/front_end/panels/ap...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../scripts/build/typescript/ts_library.py ...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/application/components/components-tsconfig.json

../../front_end/panels/application/components/StackTrace.ts(175,16): error TS2339: Property 'link' does not exist on type 'StackTraceRegularRow | StackTraceAsyncRow'.
Property 'link' does not exist on type 'StackTraceAsyncRow'.
```
##### ...The message was too long...
#### [Click here for more information](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8738273935692764865/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 9
Tag: autogenerated:cq:dry-run:1724929595
Attention: {"person_ident":"Gerrit User 1458307 \u003c1458307@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#9: Tryjobs failed"}