Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8770146853953986481) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[428/497] ACTION //test/unittests/front_end/panels/timeline/track_appenders:track_appenders(//build/toolchain/linux:x64)
FAILED: gen/test/unittests/front_end/panels/timeline/track_appenders/track_appenders-tsconfig.json g...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/unittests/fro...(too long)

TypeScript compilation failed. Used tsconfig gen/test/unittests/front_end/panels/timeline/track_appenders/track_appenders-tsconfig.json

../../test/unittests/front_end/panels/timeline/track_appenders/ThreadAppender_test.ts(481,84): error TS2339: Property 'isEntryRegularEvent' does not exist on type 'typeof TimelineFlameChartDataProvider'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run:1694532881
Attention: {"person_ident":"Gerrit User 1581285 \u003c1581285@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}