Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8750398287017846241) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5461360?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[20/623] ACTION //front_end/panels/timeline:timeline(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/timeline-tsconfig.json gen/front_end/panels/timeline/ActiveFil...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/timeline-tsconfig.json

../../front_end/panels/timeline/TimelineTreeView.ts(219,43): error TS2339: Property 'eventsForTreeView' does not exist on type 'Track'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1713366762
Attention: {"person_ident":"Gerrit User 1396442 \u003c1396442@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}