Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8783206988315278961) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[2136/2176] ACTION //test/unittests/front_end/panels/timeline:timeline(//build/toolchain/linux:x64)
FAILED: gen/test/unittests/front_end/panels/timeline/timeline-tsconfig.json gen/test/unittests/front...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/unittests/fro...(too long)

TypeScript compilation failed. Used tsconfig gen/test/unittests/front_end/panels/timeline/timeline-tsconfig.json

../../test/unittests/front_end/panels/timeline/TimelineSelection_test.ts(66,39): error TS2339: Property 'EventTypeHelpers' does not exist on type 'typeof import("/b/s/w/ir/cache/builder/devtools-frontend/out/Debug/gen/front_end/panels/timeline/timeline")'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1682078094
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}