Update patch set 5
Patch Set 5:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8876776403458156384
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [3/28] ACTION //front_end/sdk:sdk(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/TracingModel.js(231,60): error TS2339: Property 'data' does not exist on type '{ sort_index: number; name: string; snapshot: ObjectSnapshot; }'.
    ../../front_end/sdk/TracingModel.js(232,22): error TS2339: Property 'data' does not exist on type '{ sort_index: number; name: string; snapshot: ObjectSnapshot; }'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8876776318042505648
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [10/33] ACTION //front_end/sdk:sdk(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/TracingModel.js(231,60): error TS2339: Property 'data' does not exist on type '{ sort_index: number; name: string; snapshot: ObjectSnapshot; }'.
    ../../front_end/sdk/TracingModel.js(232,22): error TS2339: Property 'data' does not exist on type '{ sort_index: number; name: string; snapshot: ObjectSnapshot; }'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 5
Tag: autogenerated:cq:dry-run