Fix component bridges tests
A recent TS config change elsewhere had caused these tests not to
compile with the error of:

```
error TS6307: File '/Users/jacktfranklin/src/devtools/devtools-frontend/scripts/component_bridges/value_for_type_node.ts' is not listed within the file list of project '/Users/jacktfranklin/src/devtools/devtools-frontend/test/unittests/scripts/component_bridges/tsconfig.json'.
```

The fix is to:

- mark `rootDir` as the top level directory that contains the
  implementation and the tests (done in
  `scripts/component_bridges/tsconfig.json`)
- explicitly include the implementation files in the test
  `tsconfig.json`

Change-Id: I9a924bf3e2ed945dd22ce233eda2c8c15f3193c6