Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8750311123844635553) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5465633?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[557/806] ACTION //front_end/panels/timeline:unittests(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/unittests-tsconfig.json gen/front_end/panels/timeline/Breadcru...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/unittests-tsconfig.json

../../front_end/panels/timeline/TimelineUIUtils.test.ts(106,10): error TS2339: Property 'stackTrace' does not exist on type 'EventOnTimelineData'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1713450025
Attention: {"person_ident":"Gerrit User 1396442 \u003c1396442@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}