Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_blink_light_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8861279235837346288
    #### Step _compile (with patch)_ failed. Error logs are shown below:
    ```
    [1767/19502] ACTION //third_party/devtools-frontend/src/inspector_overlay:inspector_overlay(//build/toolchain/linux:clang_x64)
    FAILED: gen/third_party/devtools-frontend/src/inspector_overlay/inspector_overlay-tsconfig.json gen/...(too long)
    /b/s/w/ir/cipd_bin_packages/cpython/bin/python ../../third_party/devtools-frontend/src/third_party/t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/third_party/devtools-frontend/src/inspector_overlay/inspector_overlay-tsconfig.json
    
    ../../third_party/devtools-frontend/src/inspector_overlay/tool_highlight.ts(391,19): error TS2339: Property 'isLocked' does not exist on type 'ElementInfo'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run