Update patch set 3
Patch Set 3:

Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8839020422462255441
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [264/679] ACTION //front_end/panels/sources:sources-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/panels/sources/sources-tsconfig.json gen/front_end/panels/sources/AddSourceMap...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/s...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/panels/sources/sources-tsconfig.json
    
    ../../front_end/panels/sources/NavigatorView.ts(970,10): error TS2551: Property '_scriptsTree' does not exist on type 'NavigatorView'. Did you mean 'scriptsTree'?
    
    
    ```
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8839020128895495521
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [3/359] ACTION //front_end/panels/sources:sources-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/panels/sources/sources-tsconfig.json gen/front_end/panels/sources/AddSourceMap...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/s...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/panels/sources/sources-tsconfig.json
    
    ../../front_end/panels/sources/NavigatorView.ts(970,10): error TS2551: Property '_scriptsTree' does not exist on type 'NavigatorView'. Did you mean 'scriptsTree'?
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cv