Update patch set 3
Patch Set 3:

Breaks clicking in a flamechart of the legacy JavaScript profiler.
The following error is shown in devtools-on-devtools upon clicking:

Uncaught (in promise) TypeError: self.Bindings.DebuggerWorkspaceBinding.rawLocationToUILocation is not a function
    at CPUProfileView._onEntryInvoked (ProfileView.js:38)
    at CPUProfileFlameChart.dispatchEventToListeners (Object.js:12)
    at CPUProfileFlameChart._onEntryInvoked (CPUProfileFlameChart.js:24)
    at FlameChart.dispatchEventToListeners (Object.js:12)
    at FlameChart._onClick (FlameChart.js:45)

Patch-set: 3
CC: Gerrit User 1222584 <1222584@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>