Update patch set 8
Patch Set 8:

Failed builds:
  luci.devtools-frontend.try/devtools_frontend_win64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8848176360546832896
    Step('E2E tests') (retcode: 11)
  luci.devtools-frontend.try/devtools_frontend_win64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8848174964984056768
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [115/478] ACTION //front_end/models/recorder:recorder-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/models/recorder/recorder-tsconfig.json gen/front_end/models/recorder/Condition...(too long)
    C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/models/recorder/recorder-tsconfig.json
    
    b"../../front_end/models/recorder/RecordingSession.ts(115,10): error TS2339: Property 'steps' does not exist on type 'RecordingSession'.\r\n../../front_end/models/recorder/RecordingSession.ts(133,41): error TS2339: Property 'steps' does not exist on type 'RecordingSession'.\r\n"
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 8
Tag: autogenerated:cq:full-run