Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8750222395347790913) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5466288?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[230/1120] ACTION //front_end/panels/sources:sources(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/sources/sources-tsconfig.json gen/front_end/panels/sources/AddSourceMap...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/s...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/sources/sources-tsconfig.json

../../front_end/panels/sources/DebuggerPlugin.ts(1464,85): error TS2339: Property 'uiSourceCode' does not exist on type 'ResourceScriptFile'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1713534549
Attention: {"person_ident":"Gerrit User 1183894 \u003c1183894@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}