Update patch set 26
Patch Set 26:

Dry run: Failed builds:
  luci.devtools-frontend.try/dtf_presubmit_win64 JOB_FAILED https://cr-buildbucket.appspot.com/build/8809811282779114193
    There are 1 error, 0 warnings, and 15 notifications.
    
    Here are the errors:
    
    **ERROR**
    
    Script execution time was 23\.8s seconds
    
    
    
    C:\\b\\s\\w\\ir\\cache\\builder\\dtf\_presubmit\_win64\\devtools\-frontend\\test\\e2e\\helpers\\media\-helpers\.ts
    
      34:0  error  Parsing error: Merge conflict marker encountered
    
    
    
    C:\\b\\s\\w\\ir\\cache\\builder\\dtf\_presubmit\_win64\\devtools\-frontend\\test\\e2e\\media\\media\-tab\_test\.ts
    
      7:0  error  Parsing error: Merge conflict marker encountered
    
    
    
    ✖ 2 problems \(2 errors, 0 warnings\)
    
    
    
    
    
    To see notifications and warnings, look at the stdout of the presubmit step.
  luci.devtools-frontend.try/dtf_presubmit_linux JOB_FAILED https://cr-buildbucket.appspot.com/build/8809811282779114209
    There are 1 error, 0 warnings, and 15 notifications.
    
    Here are the errors:
    
    **ERROR**
    
    Script execution time was 11\.3s seconds
    
    
    
    /b/s/w/ir/cache/builder/dtf\_presubmit\_linux/devtools\-frontend/test/e2e/helpers/media\-helpers\.ts
    
      34:0  error  Parsing error: Merge conflict marker encountered
    
    
    
    /b/s/w/ir/cache/builder/dtf\_presubmit\_linux/devtools\-frontend/test/e2e/media/media\-tab\_test\.ts
    
      7:0  error  Parsing error: Merge conflict marker encountered
    
    
    
    ✖ 2 problems \(2 errors, 0 warnings\)
    
    
    
    
    
    
    
    To see notifications and warnings, look at the stdout of the presubmit step.
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8809811282779114241
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [708/3505] ACTION //test/e2e/helpers:helpers(//build/toolchain/linux:x64)
    FAILED: gen/test/e2e/helpers/helpers-tsconfig.json gen/test/e2e/helpers/animations-helpers.js gen/te...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/e2e/helpers/h...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/test/e2e/helpers/helpers-tsconfig.json
    
    ../../test/e2e/helpers/media-helpers.ts(34,1): error TS1185: Merge conflict marker encountered.
    ../../test/e2e/helpers/media-helpers.ts(35,1): error TS1185: Merge conflict marker encountered.
    ../../test/e2e/helpers/media-helpers.ts(39,1): error TS1185: Merge conflict marker encountered.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 26
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1255015 \u003c1255015@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#26: CQ dry run failed."}