Update patch set 20
Patch Set 20:

This CL has failed the run. Reason:

Failed Tryjobs:
* [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8747081590841162593). Summary ([view all results](https://chromium-review.googlesource.com/c/5551153?checksPatchset=20&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[5/872] ACTION //front_end/models/issues_manager:issues_manager(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json

../../front_end/models/issues_manager/CookieDeprecationMetadataIssue.ts(28,110): error TS2339: Property 'operation' does not exist on type 'CookieDeprecationMetadataIssueDetails'.
```
##### ...The message was too long...
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8747081590841162593/+/u/compile/raw_io.output_text_failure_summary_)

---
* [devtools-frontend/try/devtools_frontend_mac_rel](https://cr-buildbucket.appspot.com/build/8747081629139003553). Summary ([view all results](https://chromium-review.googlesource.com/c/5551153?checksPatchset=20&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1510/3613] ACTION //front_end/models/issues_manager:issues_manager(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json

../../front_end/models/issues_manager/CookieDeprecationMetadataIssue.ts(28,110): error TS2339: Property 'operation' does not exist on type 'CookieDeprecationMetadataIssueDetails'.
```
##### ...The message was too long...
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8747081629139003553/+/u/compile/raw_io.output_text_failure_summary_)

---

Patch-set: 20
Tag: autogenerated:cq:dry-run:1716529925
Attention: {"person_ident":"Gerrit User 1579342 \u003c1579342@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#20: Tryjobs failed"}