Update patch set 11
Patch Set 11:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8770072377449904705) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[93/1582] ACTION //front_end/models/extensions:extensions-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/extensions/extensions-tsconfig.json gen/front_end/models/extensions/Ext...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/extensions/extensions-tsconfig.json

../../front_end/models/extensions/ExtensionServer.ts(435,46): error TS2551: Property 'request' does not exist on type 'NetworkRequest'. Did you mean 'requestId'?


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 11
Tag: autogenerated:cq:full-run:1694604238
Attention: {"person_ident":"Gerrit User 1511722 \u003c1511722@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#11: Tryjobs failed"}