Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8739495374709651297) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5788240?checksPatchset=3&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[72/696] ACTION //front_end/panels/timeline:timeline(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/timeline-tsconfig.json gen/front_end/panels/timeline/ActiveFil...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/timeline-tsconfig.json

../../front_end/panels/timeline/TimelinePanel.ts(509,23): error TS2339: Property 'setSelection' does not exist on type 'TimelineFlameChartView'.


```
#### [Click here for more information](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8739495374709651297/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 3
Tag: autogenerated:cq:dry-run:1723764739
Attention: {"person_ident":"Gerrit User 1468649 \u003c1468649@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}