Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8757933994978783153) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/5233807?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[699/2179] ACTION //front_end/models/trace/handlers:handlers(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/trace/handlers/handlers-tsconfig.json gen/front_end/models/trace/handle...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/trace/handlers/handlers-tsconfig.json

../../front_end/models/trace/handlers/AnimationHandler.ts(11,34): error TS2314: Generic type 'SyntheticNestableAsyncEvent<T>' requires 1 type argument(s).
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1706180293
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}