Update patch set 4
Patch Set 4:

Try jobs failed on following builders:
  luci.devtools-frontend.try/devtools_frontend_presubmit JOB_FAILED https://ci.chromium.org/b/8898699557472368880
    There are 2 error(s), 0 warning(s), and 0 notifications(s). Here are the errors:
    
    **ERROR**
    
    internal/modules/cjs/loader.js:584
    
        throw err;
    
        ^
    
    
    
    Error: Cannot find module '/b/s/w/ir/cache/builder/devtools_frontend_presubmit/devtools-frontend/node_modules/esprima'
    
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    
        at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    
        at Module.require (internal/modules/cjs/loader.js:637:17)
    
        at require (internal/modules/cjs/helpers.js:22:18)
    
    **Error size > 450 chars, there are 7 more error(s) (17 total)**
    
    **The complete output can be found at the bottom of the presubmit stdout.**
  luci.devtools-frontend.try/devtools_frontend_presubmit JOB_FAILED https://ci.chromium.org/b/8898699179934322528
    There are 2 error(s), 0 warning(s), and 0 notifications(s). Here are the errors:
    
    **ERROR**
    
    internal/modules/cjs/loader.js:584
    
        throw err;
    
        ^
    
    
    
    Error: Cannot find module '/b/s/w/ir/cache/builder/devtools_frontend_presubmit/devtools-frontend/node_modules/esprima'
    
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    
        at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    
        at Module.require (internal/modules/cjs/loader.js:637:17)
    
        at require (internal/modules/cjs/helpers.js:22:18)
    
    **Error size > 450 chars, there are 7 more error(s) (17 total)**
    
    **The complete output can be found at the bottom of the presubmit stdout.**

Patch-set: 4
Tag: autogenerated:cq:full-run