Update patch set 1
Patch Set 1:

Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8822253783429934289
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [912/2026] ACTION //front_end/models/issues_manager:issues_manager-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json
    
    ../../front_end/models/issues_manager/FederatedAuthRequestIssue.ts(96,53): error TS2339: Property 'WellKnownHttpNotFound' does not exist on type 'typeof FederatedAuthRequestIssueReason'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8822253594933224145
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [900/2026] ACTION //front_end/models/issues_manager:issues_manager-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json
    
    ../../front_end/models/issues_manager/FederatedAuthRequestIssue.ts(96,53): error TS2339: Property 'WellKnownHttpNotFound' does not exist on type 'typeof FederatedAuthRequestIssueReason'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1439900 \u003c1439900@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: CQ full run failed."}