Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8769337532052882865) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/4879805?checksPatchset=2&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[86/269] ACTION //front_end/panels/recorder/models:recorder-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/recorder/models/recorder-tsconfig.json gen/front_end/panels/recorder/mo...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/r...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/recorder/models/recorder-tsconfig.json

../../front_end/panels/recorder/models/RecordingPlayer.ts(178,32): error TS2551: Property '_client' does not exist on type 'Frame'. Did you mean 'client'?


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run:1695304920
Attention: {"person_ident":"Gerrit User 1410814 \u003c1410814@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}