Update patch set 4
Patch Set 4:

This CL has failed the run. Reason:

Failed Tryjobs:
* [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8753147581531848849). Summary ([view all results](https://chromium-review.googlesource.com/c/5347319?checksPatchset=4&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[727/2222] ACTION //front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/NetworkRequest.ts(1480,10): error TS2540: Cannot assign to '#initiatorInternal' because it is a read-only property.


```
#### More information in raw_io.output_text[failure_summary]

---
* [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8753147581531848769). Summary ([view all results](https://chromium-review.googlesource.com/c/5347319?checksPatchset=4&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[44/2305] ACTION //front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/NetworkRequest.ts(1480,10): error TS2540: Cannot assign to '#initiatorInternal' because it is a read-only property.


```
#### More information in raw_io.output_text[failure_summary]

---

Patch-set: 4
Tag: autogenerated:cq:dry-run:1710744979
Attention: {"person_ident":"Gerrit User 1343440 \u003c1343440@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#4: Tryjobs failed"}