Update patch set 4
Patch Set 4:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8739637369000642977) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5783824?checksPatchset=4&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1340/2367] ACTION //front_end/panels/network:network(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/network/network-tsconfig.json gen/front_end/panels/network/BinaryResour...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/n...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/network/network-tsconfig.json

../../front_end/panels/network/RequestTimingView.ts(539,39): error TS2339: Property 'metric' does not exist on type 'ServerTiming'.
../../front_end/panels/network/RequestTimingView.ts(541,39): error TS2339: Property 'metric' does not exist on type 'ServerTiming'.
```
##### ...The message was too long...
#### [Click here for more information](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8739637369000642977/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 4
Tag: autogenerated:cq:dry-run:1723629323
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#4: Tryjobs failed"}