Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8880883416483067664
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [363/415] ACTION //front_end/sdk:sdk(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/MixedContentIssue.js(87,13): error TS2339: Property 'createChild' does not exist on type 'HTMLDivElement'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run