Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8755021056090039633) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/5324005?checksPatchset=3&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1059/2217] ACTION //front_end/ui/legacy:ui(//build/toolchain/linux:x64)
FAILED: gen/front_end/ui/legacy/ui-tsconfig.json gen/front_end/ui/legacy/ARIAUtils.js gen/front_end/...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/legac...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/ui/legacy/ui-tsconfig.json

../../front_end/ui/legacy/UIUtils.ts(1137,85): error TS2749: 'Option' refers to a value, but is being used as a type here. Did you mean 'typeof Option'?


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run:1708958296
Attention: {"person_ident":"Gerrit User 1511722 \u003c1511722@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}