Update patch set 1
Patch Set 1:

Liviu, PTAL the following:

> Error: Cannot find module 'C:\b\s\w\ir\cache\builder\node_modules\stylelint\bin\stylelint.js'

The file is checked in to the repo here: https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/node_modules/stylelint/bin/stylelint.js

Any idea why this would be missing from the builder cache on the Windows bot?

Patch-set: 1
Reviewer: Gerrit User 1368998 <1368998@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0