Update patch set 4
Patch Set 4:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8768087376263279393) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/4909550?checksPatchset=4&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[9/555] ACTION //test/interactions/panels/performance/timeline:timeline(//build/toolchain/linux:x64)
FAILED: gen/test/interactions/panels/performance/timeline/timeline-tsconfig.json gen/test/interactio...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/interactions/...(too long)

TypeScript compilation failed. Used tsconfig gen/test/interactions/panels/performance/timeline/timeline-tsconfig.json

error TS5055: Cannot write file '/b/s/w/ir/cache/builder/devtools-frontend/front_end/generated/InspectorBackendCommands.js' because it would overwrite input file.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 4
Tag: autogenerated:cq:dry-run:1696497111
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#4: Tryjobs failed"}