Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8855664654392765168
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [23/2938] ACTION //front_end/common:common-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/common/common-tsconfig.json gen/front_end/common/common-tsconfig.json.tsbuildi...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/common/co...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/common/common-tsconfig.json
    
    error TS5055: Cannot write file '/b/s/w/ir/cache/builder/devtools-frontend/front_end/host/InspectorFrontendHost.js' because it would overwrite input file.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8855664465534728784
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [3/2914] ACTION //front_end/common:common-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/common/common-tsconfig.json gen/front_end/common/common-tsconfig.json.tsbuildi...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/common/co...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/common/common-tsconfig.json
    
    error TS5055: Cannot write file '/b/s/w/ir/cache/builder/devtools-frontend/front_end/host/InspectorFrontendHost.js' because it would overwrite input file.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run