Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/dtf_linux_rel](https://cr-buildbucket.appspot.com/build/8737829456301812929) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5830445?checksPatchset=3&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[61/83] ACTION //test/unit:karma(//build/toolchain/linux:x64)
FAILED: gen/test/unit/karma-tsconfig.json gen/test/unit/karma.conf.js gen/test/unit/karma.conf.js.map gen/test/unit/karma.conf.d.ts
python3 ../../scripts/build/typescript/ts_library.py --tsconfig_output_location gen/test/unit/karma-tsconfig.json --deps ../shared/shared-tsconfig.json --front_end_directory ../../test/unit --test-only --module=commonjs --reset_timestamps --sources ../../test/unit/karma.conf.ts

TypeScript compilation failed. Used tsconfig gen/test/unit/karma-tsconfig.json

../../test/unit/karma.conf.ts(26,18): error TS2339: Property 'coverage' does not exist on type 'Config'.
```
##### ...The message was too long...
#### [Click here for more information](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8737829328043366897/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 3
Tag: autogenerated:cq:dry-run:1725353483
Attention: {"person_ident":"Gerrit User 1410814 \u003c1410814@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}