Update patch set 1
Patch Set 1:

> Patch Set 1: Code-Review+1
> 
> Could you change your catch-binding to make it optional to make sure it actually works? Just as a sanity check.

Good suggestion. Unfortunately although this patch makes eslint work, there are other issues when adopting optional catch, since Esprima doesn't yet support it:

Error: DevTools localization parser failed:
front_end/persistence/WorkspaceSettingsTab.js: Line 74: Unexpected token {
This error is likely due to unsupported JavaScript features. Such features are not supported by eslint either and will cause presubmit to fail. Please update the code and use official JavaScript features.
    at parseLocalizableStringsFromFile (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/scripts/localization_utils/check_localized_strings.js:236:11)


{ Error: Line 74: Unexpected token {
    at ErrorHandler.constructError (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/node_modules/esprima/dist/esprima.js:5074:22)
    at ErrorHandler.createError (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/node_modules/esprima/dist/esprima.js:5090:27)
    at Parser.unexpectedTokenError (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/node_modules/esprima/dist/esprima.js:1996:39)
    at Parser.throwUnexpectedToken (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/node_modules/esprima/dist/esprima.js:2006:21)
    at Parser.expect (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/node_modules/esprima/dist/esprima.js:2179:19)
    at Parser.parseCatchClause (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/node_modules/esprima/dist/esprima.js:4111:15)
    at Parser.parseTryStatement (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/node_modules/esprima/dist/esprima.js:4142:58)
    at Parser.parseStatement (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/node_modules/esprima/dist/esprima.js:4219:43)
    at Parser.parseStatementListItem (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/node_modules/esprima/dist/esprima.js:3431:39)
    at Parser.parseFunctionSourceElements (/usr/local/google/home/mathiasb/projects/devtools/devtools-frontend/node_modules/esprima/dist/esprima.js:4257:29)
  index: 3204,
  lineNumber: 74,
  description: 'Unexpected token {' }

I'll close this CL for now.

Patch-set: 1
Reviewer: Gerrit User 1214214 <1214214@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0