Update patch set 12
Patch Set 12:

(8 comments)

I started user testing this CL and I found some bugs. I have updated the user stories doc with the user story. TLDR: closing a tab is broken. It throws with

[56352:775:0520/120836.665961:ERROR:CONSOLE(172)] "Uncaught TypeError: this._delegate.closeTabs is not a function", source: devtools://devtools/bundled/ui/TabbedPane.js (172)

Also: since the console is both in the drawer and in the main panel, when I "Move to main panel" the console in the drawer, I have 2 consoles in the main panel.

Can we have e2e-tests for these scenarios prior to landing this CL to make sure we don't regress?

Patch-set: 12
Reviewer: Gerrit User 1365394 <1365394@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>