Update patch set 6
Patch Set 6:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8866258342812579264
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [862/950] ACTION //front_end/resources:resources-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/resources/resources-tsconfig.json gen/front_end/resources/resources-tsconfig.j...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/resources...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/resources/resources-tsconfig.json
    
    ../../front_end/resources/ClearStorageView.js(244,33): error TS2339: Property 'invoke_overrideQuotaForOrigin' does not exist on type 'StorageApi'.
    ../../front_end/resources/ClearStorageView.js(257,35): error TS2339: Property 'invoke_overrideQuotaForOrigin' does not exist on type 'StorageApi'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8866258028268238192
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [846/934] ACTION //front_end/resources:resources-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/resources/resources-tsconfig.json gen/front_end/resources/resources-tsconfig.j...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/resources...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/resources/resources-tsconfig.json
    
    ../../front_end/resources/ClearStorageView.js(244,33): error TS2339: Property 'invoke_overrideQuotaForOrigin' does not exist on type 'StorageApi'.
    ../../front_end/resources/ClearStorageView.js(257,35): error TS2339: Property 'invoke_overrideQuotaForOrigin' does not exist on type 'StorageApi'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 6
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1302791 \u003c1302791@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"Someone else replied on the change"}