Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8850135327484111504
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [277/2283] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/sdk-tsconfig.json.tsbuildinf...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk/...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/CSSMatchedStyles.ts(709,9): error TS2578: Unused '@ts-expect-error' directive.
    ../../front_end/core/sdk/CSSMatchedStyles.ts(711,27): error TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
    Type 'null' is not assignable to type 'string'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8850135181003923472
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [284/2290] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/sdk-tsconfig.json.tsbuildinf...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk/...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/CSSMatchedStyles.ts(709,9): error TS2578: Unused '@ts-expect-error' directive.
    ../../front_end/core/sdk/CSSMatchedStyles.ts(711,27): error TS2345: Argument of type 'string | null' is not assignable to parameter of type 'string'.
    Type 'null' is not assignable to type 'string'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run