Update patch set 1
Patch Set 1:

This fixes VSCode 👍, however it doesn't fix running the tests via Karma:

```
> chrome-devtools-frontend@ unittest /Users/jacktfranklin/src/devtools/devtools-frontend
> NO_TEXT_COVERAGE=1 python scripts/test/run_unittests.py

Using Chromium binary (/Users/jacktfranklin/src/devtools/devtools-frontend/third_party/chrome/chrome-mac/Chromium.app/Contents/MacOS/Chromium)

10 03 2020 12:24:58.084:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.8.3
10 03 2020 12:25:01.920:ERROR [compiler.karma-typescript]: front_end/elements/ElementsBreadcrumbs.ts(38,28): error TS2304: Cannot find name 'ResizeObserver'.

10 03 2020 12:25:01.920:ERROR [compiler.karma-typescript]: front_end/elements/ElementsBreadcrumbs.ts(58,31): error TS2304: Cannot find name 'ResizeObserver'.
```

This might be OK because we _have_ to move all the tests to Ninja for the Breadcrumbs work to land, WDYT?

Patch-set: 1
Reviewer: Gerrit User 1396442 <1396442@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>