Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8763283844619017345) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/5060293?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[64/623] ACTION //front_end/panels/timeline:timeline(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/timeline-tsconfig.json gen/front_end/panels/timeline/Animation...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/timeline-tsconfig.json

../../front_end/panels/timeline/TimelineUIUtils.ts(1817,69): error TS2345: Argument of type 'CompatibleTraceEvent' is not assignable to parameter of type 'TraceEventData'.
Type 'Event' is missing the following properties from type 'TraceEventData': cat, ph, pid, tid, ts


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1701078192
Attention: {"person_ident":"Gerrit User 1396442 \u003c1396442@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}