Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8780254697730930481) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[2/2516] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/PreloadingModel.ts(246,11): error TS2741: Property 'prefetchStatus' is missing in type '{ action: Protocol.Preload.SpeculationAction.Prefetch; key: Protocol.Preload.PreloadingAttemptKey; status: PreloadingStatus; }' but required in type 'PrefetchAttemptInternal'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run:1684893507
Attention: {"person_ident":"Gerrit User 1517927 \u003c1517927@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}