Make NetworkManager deal with i18n key changes
I hit a fun issue with i18nkeys and the serialization of the saved
network connection types today:

1. On another branch for another CL, I renamed the i18n keys for the
   throttling presets and added some new ones.
2. Then, back on origin/main, I got an error:
   ```
   Error: Unable to locate 'Fast 4G' in UIStrings object", source:
   devtools://devtools/bundled/third_party/i18n/localized-string-set.js
   (41)
   ```
3. I then realised this was due to my network throttling preference
   being stored, but the i18n keys changing since it was stored.

Of course this shouldn't occur in real life and we should maintan the
keys to avoid it, but this CL updates the two places in the code which
threw the error above, just so that if this ever does happen for real we
don't break the panel for users.

Bug: none
Change-Id: Ic28e1bd47dada582051e3b69457fed82f5832b66