Update patch set 9
Patch Set 9:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8800061191636003777) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[1735/2107] ACTION //front_end/panels/timeline:timeline-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/timeline-tsconfig.json gen/front_end/panels/timeline/CLSLinkif...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/timeline-tsconfig.json

../../front_end/panels/timeline/TimelinePanel.ts(998,56): error TS2339: Property 'NamesResolved' does not exist on type 'typeof Events'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 9
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#9: Tryjobs failed"}