Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8784108161496213345) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[1769/2176] ACTION //front_end/panels/timeline:timeline-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/timeline-tsconfig.json gen/front_end/panels/timeline/CLSLinkif...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/timeline-tsconfig.json

../../front_end/panels/timeline/TimelineFlameChartView.ts(264,11): error TS1361: 'TraceEngine' cannot be used as a value because it was imported using 'import type'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1681218633
Attention: {"person_ident":"Gerrit User 1396442 \u003c1396442@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}