Update patch set 11
Patch Set 11:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_mac_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8881041267217940080
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [39/113] ACTION //front_end/sdk:sdk(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/NetworkManager.js(65,7): error TS2304: Cannot find name 'his'.
    ../../front_end/sdk/NetworkManager.js(1086,19): error TS2339: Property 'userAgentData' does not exist on type 'Navigator'.
    ../../front_end/sdk/NetworkManager.js(1087,24): error TS2339: Property 'userAgentData' does not exist on type 'Navigator'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8881041267217940096
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [65/113] ACTION //front_end/sdk:sdk(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/NetworkManager.js(65,7): error TS2304: Cannot find name 'his'.
    ../../front_end/sdk/NetworkManager.js(1086,19): error TS2339: Property 'userAgentData' does not exist on type 'Navigator'.
    ../../front_end/sdk/NetworkManager.js(1087,24): error TS2339: Property 'userAgentData' does not exist on type 'Navigator'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 11
Tag: autogenerated:cq:dry-run