Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8824680336100708801
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [727/2014] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/ServiceWorkerCacheModel.ts(27,14): error TS2420: Class 'ServiceWorkerCacheModel' incorrectly implements interface 'StorageDispatcher'.
    Property 'interestGroupAccessed' is missing in type 'ServiceWorkerCacheModel' but required in type 'StorageDispatcher'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_win64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8824680336100708769
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [28/2189] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/ServiceWorkerCacheModel.ts(27,14): error TS2420: Class 'ServiceWorkerCacheModel' incorrectly implements interface 'StorageDispatcher'.
    Property 'interestGroupAccessed' is missing in type 'ServiceWorkerCacheModel' but required in type 'StorageDispatcher'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1444807 \u003c1444807@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: CQ dry run failed."}