Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8858180727132854368
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [314/2439] ACTION //front_end/ui:ui-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/ui/ui-tsconfig.json gen/front_end/ui/ui-tsconfig.json.tsbuildinfo gen/front_en...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/ui-tsc...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/ui/ui-tsconfig.json
    
    ../../front_end/ui/ViewManager.js(53,67): error TS2339: Property 'TRANSIENT' does not exist on type 'typeof ViewPersistence'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8858180538206346384
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [292/2442] ACTION //front_end/ui:ui-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/ui/ui-tsconfig.json gen/front_end/ui/ui-tsconfig.json.tsbuildinfo gen/front_en...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/ui-tsc...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/ui/ui-tsconfig.json
    
    ../../front_end/ui/ViewManager.js(53,67): error TS2339: Property 'TRANSIENT' does not exist on type 'typeof ViewPersistence'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run