Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/dtf_presubmit_linux JOB_FAILED https://cr-buildbucket.appspot.com/build/8857125238861233696
    There are 3 errors, 0 warnings, and 21 notifications.
    
    Here are the errors:
    
    **ERROR**
    
    Script execution time was 12\.7s seconds
    
    Verifying all resources are localizable and checking the structure of grd files\.\.\.
    
    Error: Found changes to localizable DevTools resources\.
    
    DevTools localizable resources checker has updated the appropriate grd/grdp file\(s\)\.
    
    
    
    Unused string found in UIStrings\.
    
    Replaced UIStrings in /b/s/w/ir/cache/builder/dtf\_presubmit\_linux/devtools\-frontend/front\_end/browser\_sdk/ModuleUIStrings\.js
    
    
    
    **Error size > 450 chars, there are 6 more error(s) (15 total)**
    
    **The complete output can be found at the bottom of the presubmit stdout.**
    
    To see notifications and warnings, look at the stdout of the presubmit step.
  luci.devtools-frontend.try/dtf_presubmit_linux JOB_FAILED https://cr-buildbucket.appspot.com/build/8857125113199183216
    There are 3 errors, 0 warnings, and 21 notifications.
    
    Here are the errors:
    
    **ERROR**
    
    Script execution time was 11\.6s seconds
    
    Verifying all resources are localizable and checking the structure of grd files\.\.\.
    
    Error: Found changes to localizable DevTools resources\.
    
    DevTools localizable resources checker has updated the appropriate grd/grdp file\(s\)\.
    
    
    
    Unused string found in UIStrings\.
    
    Replaced UIStrings in /b/s/w/ir/cache/builder/dtf\_presubmit\_linux/devtools\-frontend/front\_end/browser\_sdk/ModuleUIStrings\.js
    
    
    
    **Error size > 450 chars, there are 6 more error(s) (15 total)**
    
    **The complete output can be found at the bottom of the presubmit stdout.**
    
    To see notifications and warnings, look at the stdout of the presubmit step.

Patch-set: 1
Tag: autogenerated:cq:dry-run