Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_win64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8814476311476421265
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [69/2067] ACTION //front_end/models/issues_manager:issues_manager-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
    C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json
    
    ../../front_end/models/issues_manager/AttributionReportingIssue.ts(22,83): error TS2366: Function lacks ending return statement and return type does not include 'undefined'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1323977 \u003c1323977@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: CQ dry run failed."}