Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob `devtools-frontend/try/devtools_frontend_linux_rel` has failed: https://cr-buildbucket.appspot.com/build/8800754915124897313
	#### Step _compile_ failed. Error logs are shown below:
	```
	[23/108] ACTION //test/unittests/front_end/core/sdk:sdk(//build/toolchain/linux:x64)
	FAILED: gen/test/unittests/front_end/core/sdk/sdk-tsconfig.json gen/test/unittests/front_end/core/sd...(too long)
	python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/unittests/fro...(too long)
	
	TypeScript compilation failed. Used tsconfig gen/test/unittests/front_end/core/sdk/sdk-tsconfig.json
	
	../../test/unittests/front_end/core/sdk/NetworkRequest_test.ts(12,28): error TS2339: Property 'parseStatusTextFromResponseHeadersText' does not exist on type 'typeof import("/b/s/w/ir/cache/builder/devtools-frontend/out/Release/gen/front_end/core/sdk/NetworkRequest")'.
	```
	##### ...The message was too long...
	#### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Attention: {"person_ident":"Gerrit User 1303398 \u003c1303398@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}