Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8866520757907625552
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [60/999] ACTION //front_end/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/NetworkRequest.js(1655,47): error TS2339: Property 'SchemefulSameSiteStrict' does not exist on type 'typeof CookieBlockedReason'.
    ../../front_end/sdk/NetworkRequest.js(1657,47): error TS2339: Property 'SchemefulSameSiteLax' does not exist on type 'typeof CookieBlockedReason'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8866520653478328288
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1/924] ACTION //front_end/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/NetworkRequest.js(1655,47): error TS2339: Property 'SchemefulSameSiteStrict' does not exist on type 'typeof CookieBlockedReason'.
    ../../front_end/sdk/NetworkRequest.js(1657,47): error TS2339: Property 'SchemefulSameSiteLax' does not exist on type 'typeof CookieBlockedReason'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1316595 \u003c1316595@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"Someone else replied on the change"}