Update patch set 6
Patch Set 6:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8747071355360330465) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5548295?checksPatchset=6&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[29/675] ACTION //front_end/panels/network:network(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/network/network-tsconfig.json gen/front_end/panels/network/BinaryResour...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/n...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/network/network-tsconfig.json

../../front_end/panels/network/RequestTimingView.ts(381,37): error TS2551: Property 'SendStart' does not exist on type 'ResourceTiming'. Did you mean 'sendStart'?


```
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8747071355360330465/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 6
Tag: autogenerated:cq:dry-run:1716539286
Attention: {"person_ident":"Gerrit User 3362409 \u003c3362409@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: Tryjobs failed"}