Update patch set 12
Patch Set 12:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8747195095779202545) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5551153?checksPatchset=12&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[878/2231] ACTION //front_end/models/issues_manager:issues_manager(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json

../../front_end/models/issues_manager/CookieDeprecationMetadataIssue.ts(32,3): error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Issue<string>'.
```
##### ...The message was too long...
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8747195095779202545/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 12
Tag: autogenerated:cq:dry-run:1716421714
Attention: {"person_ident":"Gerrit User 1579342 \u003c1579342@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#12: Tryjobs failed"}