Update patch set 9
Patch Set 9:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_win64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8836572403532091009
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [30/2203] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/EmulationModel.ts(290,31): error TS2339: Property 'invoke_setAutoDarkModeOverride' does not exist on type 'EmulationApi'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_win64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8836572130828669633
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [28/2201] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/EmulationModel.ts(290,31): error TS2339: Property 'invoke_setAutoDarkModeOverride' does not exist on type 'EmulationApi'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 9
Tag: autogenerated:cv