Update patch set 6
Patch Set 6:

This CL has failed the run. Reason:

Failed Tryjobs:
* [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8747043866823572833). Summary ([view all results](https://chromium-review.googlesource.com/c/5526182?checksPatchset=6&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1751/2249] ACTION //front_end/panels/application:application(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/application/application-tsconfig.json gen/front_end/panels/application/...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/a...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/application/application-tsconfig.json

../../front_end/panels/application/ServiceWorkersView.ts(662,18): error TS2339: Property 'disableHeaderButtons' does not exist on type 'Section'.


```
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8747043866823572833/+/u/compile/raw_io.output_text_failure_summary_)

---
* [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8747043694279854225). Summary ([view all results](https://chromium-review.googlesource.com/c/5526182?checksPatchset=6&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[545/1115] ACTION //front_end/panels/application:application(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/application/application-tsconfig.json gen/front_end/panels/application/...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/a...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/application/application-tsconfig.json

../../front_end/panels/application/ServiceWorkersView.ts(662,18): error TS2339: Property 'disableHeaderButtons' does not exist on type 'Section'.


```
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8747043694279854225/+/u/compile/raw_io.output_text_failure_summary_)

---

Patch-set: 6
Tag: autogenerated:cq:full-run:1716565937
Attention: {"person_ident":"Gerrit User 1419627 \u003c1419627@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: Tryjobs failed"}
Attention: {"person_ident":"Gerrit User 1380460 \u003c1380460@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: Tryjobs failed"}