Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8842200208503784832
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [6/2059] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/OverlayModel.ts(693,23): error TS2339: Property 'containerQueryContainerHighlightConfig' does not exist on type 'HighlightConfig'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8842200103940846784
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [6/2059] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/OverlayModel.ts(693,23): error TS2339: Property 'containerQueryContainerHighlightConfig' does not exist on type 'HighlightConfig'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cv