Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8768087475609769457) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/4914175?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[43/722] ACTION //test/interactions/panels/performance/timeline:timeline(//build/toolchain/linux:x64)
FAILED: gen/test/interactions/panels/performance/timeline/timeline-tsconfig.json gen/test/interactio...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/test/interactions/panels/performance/timeline/timeline-tsconfig.json

error TS5055: Cannot write file 'C:/b/s/w/ir/cache/builder/devtools-frontend/front_end/generated/InspectorBackendCommands.js' because it would overwrite input file.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1696497185
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}