Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8787094754745105489) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[1607/2155] ACTION //front_end/panels/timeline:timeline-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/timeline-tsconfig.json gen/front_end/panels/timeline/CLSLinkif...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/timeline-tsconfig.json

../../front_end/panels/timeline/TimelineUIUtils.ts(2108,52): error TS2339: Property 'NestableAsyncInstant' does not exist on type 'typeof Phase'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1678370249
Attention: {"person_ident":"Gerrit User 1396442 \u003c1396442@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}