Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8772096161454128913) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[1461/2447] ACTION //front_end/panels/sources:sources-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/sources/sources-tsconfig.json gen/front_end/panels/sources/AddSourceMap...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/s...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/sources/sources-tsconfig.json

../../front_end/panels/sources/SourcesSearchScope.ts(310,65): error TS2339: Property 'columnNumber' does not exist on type 'SearchMatch'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run:1692674206