Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8839253754072248736
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [126/606] ACTION //front_end/panels/media:media-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/panels/media/media-tsconfig.json gen/front_end/panels/media/EventDisplayTable....(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/m...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/panels/media/media-tsconfig.json
    
    ../../front_end/panels/media/PlayerPropertiesView.ts(589,10): error TS2551: Property '_mediaElements' does not exist on type 'PlayerPropertiesView'. Did you mean 'mediaElements'?
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cv