Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8742790318329773505) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5688752?checksPatchset=2&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2062/2313] ACTION //front_end/panels/timeline:unittests(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/unittests-tsconfig.json gen/front_end/panels/timeline/Breadcru...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/unittests-tsconfig.json

../../front_end/panels/timeline/TimelineUIUtils.test.ts(737,87): error TS2339: Property 'flameChartEntries' does not exist on type 'ExtensionTrackData'.


```
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8742790318329773505/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 2
Tag: autogenerated:cq:dry-run:1720622437
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}