Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8801863505880554369
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [932/2103] ACTION //front_end/models/issues_manager:issues_manager-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json
    
    ../../front_end/models/issues_manager/DeprecationIssue.ts(462,49): error TS2339: Property 'PaymentInstruments' does not exist on type 'typeof DeprecationIssueType'.
    
    
    ```
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1002114 \u003c1002114@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: CQ dry run failed."}