Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8761641450400206769) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/5123452?checksPatchset=3&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[241/524] ACTION //front_end/ui/components/docs/performance_panel:ts(//build/toolchain/linux:x64)
FAILED: gen/front_end/ui/components/docs/performance_panel/ts-tsconfig.json gen/front_end/ui/compone...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/compo...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/ui/components/docs/performance_panel/ts-tsconfig.json

../../front_end/ui/components/docs/performance_panel/basic.ts(135,8): error TS2339: Property 'loadFromFile' does not exist on type 'Window & typeof globalThis'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:full-run:1702643668
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}