Update patch set 6
Patch Set 6:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8835476756526258833
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [731/1962] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/NetworkRequest.ts(1511,47): error TS2339: Property 'NameValuePairExceedsMaxSize' does not exist on type 'typeof CookieBlockedReason'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_win64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8835476756526258785
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [107/2286] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/NetworkRequest.ts(1511,47): error TS2339: Property 'NameValuePairExceedsMaxSize' does not exist on type 'typeof CookieBlockedReason'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 6
Tag: autogenerated:cv