Revert "[cleanup] Turn 'Revealer' from an abstract class into an interface"
This reverts commit 96c4fcbeae82046791b976f75fdbda610442bbe0.

Reason for revert:
TypeScript compilation failed:

```
TypeScript compilation failed. Used tsconfig gen/front_end/panels/sources/sources-tsconfig.json

../../front_end/panels/sources/SourcesSearchScope.ts(310,65): error TS2339: Property 'columnNumber' does not exist on type 'SearchMatch'.
```

Presumably, the original CL depends on the reverted CL [1].
We'll tentatively revert it because the revert CL [2] for [1] landed.

[1] https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4797648
[2] https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4797745

Original change's description:
> [cleanup] Turn 'Revealer' from an abstract class into an interface
>
> Nearly all use-sites use TS `implements` already and I didn't find any
> 'instanceof' checks where a concrete Revealer class would be needed.
>
> R=alexrudenko@chromium.org
>
> Bug: 1468875
> Change-Id: I4f371d8a2e036d05e53e4e9e1b9830e4917f0be4
> Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4797649
> Commit-Queue: Simon Zünd <szuend@chromium.org>
> Reviewed-by: Alex Rudenko <alexrudenko@chromium.org>
> Commit-Queue: Alex Rudenko <alexrudenko@chromium.org>
> Auto-Submit: Simon Zünd <szuend@chromium.org>

Bug: 1468875
Change-Id: I55be2688f7b8faf3993894e0bf59f6aae3326606
No-Presubmit: true
No-Tree-Checks: true
No-Try: true