Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8781510094496539777) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[1266/2295] ACTION //front_end/panels/application/preloading/components:components-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/application/preloading/components/components-tsconfig.json gen/front_en...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/application/preloading/components/components-tsconfig.json

../../front_end/panels/application/preloading/components/PreloadingDetailsReportView.ts(76,75): error TS2366: Function lacks ending return statement and return type does not include 'undefined'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1683696380
Attention: {"person_ident":"Gerrit User 1517927 \u003c1517927@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}