Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8862557786280902496
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1007/3797] ACTION //front_end/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/NetworkManager.js(534,16): error TS7053: Element implicitly has an 'any' type because expression of type 'ResourceType' can't be used to index type 'typeof resourceTypes'.
    Property '[ResourceType.Preflight]' does not exist on type 'typeof resourceTypes'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run