Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8792164447701925553) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[759/2174] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/CookieModel.ts(92,25): error TS2339: Property 'sameParty' does not exist on type 'Cookie'.
../../front_end/core/sdk/NetworkRequest.ts(1673,29): error TS2339: Property 'SameParty' does not exist on type 'typeof Attributes'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1673535598
Attention: {"person_ident":"Gerrit User 1467227 \u003c1467227@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}