Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8767523651724384961) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/4930898?checksPatchset=2&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[4/561] ACTION //front_end/panels/timeline:timeline-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/timeline-tsconfig.json gen/front_end/panels/timeline/Animation...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/timeline-tsconfig.json

../../front_end/panels/timeline/TimelinePanel.ts(1169,23): error TS2345: Argument of type 'MilliSeconds' is not assignable to parameter of type 'Window'.
Type 'Number & { _tag: "MilliSeconds"; }' is missing the following properties from type 'Window': left, right


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run:1697034708
Attention: {"person_ident":"Gerrit User 1396442 \u003c1396442@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}