Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8776511875576573377) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[95/2376] ACTION //front_end/models/issues_manager:issues_manager-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json

../../front_end/models/issues_manager/CorsIssue.ts(49,67): error TS2366: Function lacks ending return statement and return type does not include 'undefined'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run:1688462814
Attention: {"person_ident":"Gerrit User 1372423 \u003c1372423@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}