Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8737307052828262849) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5844248?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[128/1506] ACTION //front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../scripts/build/typescript/ts_library.py ...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/NetworkRequest.ts(1861,53): error TS2339: Property 'CorsOptIn' does not exist on type 'typeof CookieExemptionReason'.


```
#### [Click here for more information](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8737307052828262849/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 1
Tag: autogenerated:cq:dry-run:1725851341