Update patch set 4
Patch Set 4:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8767586402813830833) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/4928888?checksPatchset=4&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[16/2562] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/ChildTargetManager.ts(200,58): error TS2339: Property 'DebuggerModel' does not exist on type 'typeof DebuggerModel'.
../../front_end/core/sdk/ChildTargetManager.ts(202,30): error TS2339: Property 'isReadyToPause' does not exist on type 'SDKModel<any>'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 4
Tag: autogenerated:cq:dry-run:1696974981
Attention: {"person_ident":"Gerrit User 1294707 \u003c1294707@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#4: Tryjobs failed"}