Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8737657891836223905) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5836934?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[709/1134] ACTION //front_end/core/sdk:unittests(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/unittests-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.tes...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../scripts/build/typescript/ts_library.py ...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/unittests-tsconfig.json

../../front_end/core/sdk/SourceMapScopeChainEntry.test.ts(53,7): error TS2353: Object literal may only specify known properties, and 'isScope' does not exist in type 'GeneratedRange'.
```
##### ...The message was too long...
#### [Click here for more information](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8737657891836223905/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 1
Tag: autogenerated:cq:dry-run:1725517091
Attention: {"person_ident":"Gerrit User 1323977 \u003c1323977@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}