Use parsed longhands from backend in the Styles pane
This CL utilizes the new backend field in CSS.CSSProperty (added in [1])
to populate longhand components of a shorthand property. This fixes a
few issues where the frontend can only show computed/final values of
longhand properties, resulting in confusion over how a shorthand can
possibly derive into certain longhands (they can't). Now we use parsed
values instead of computed/final values for these longhands, with one
exception: when the shorthand property value contains var() functions,
per spec Blink cannot meaningfully parse the shorthand until the var()
has been substituted. Therefore we show empty values for these longhands
as a consistent behavior with what we are currently doing.

Design doc: https://docs.google.com/document/d/1Z5qA-w0yJojHMpI4ZGDuAS1sunFpLK7byIg68VzQfkU/edit

[1]: https://crrev.com/c/3825959

Fixed: 471601
Change-Id: Idcaaad32cf43cf06a11dda455e50a86c71ba16e7