Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8880589752339813392
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [3/21] ACTION //front_end/sdk:sdk(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/CSSMedia.js(62,65): error TS2339: Property 'fromObject' does not exist on type 'typeof import("/b/s/w/ir/cache/builder/devtools-frontend/out/Release/gen/front_end/text_utils/TextRange")'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run