Update patch set 18
Patch Set 18:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8768733370789282177) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/4671155?checksPatchset=18&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[284/1265] ACTION //front_end/panels/elements:elements-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/elements/elements-tsconfig.json gen/front_end/panels/elements/Accessibi...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/elements/elements-tsconfig.json

../../front_end/panels/elements/ElementsTreeElement.ts(2188,14): error TS2339: Property 'playerID' does not exist on type 'DOMNode'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 18
Tag: autogenerated:cq:dry-run:1695881214
Attention: {"person_ident":"Gerrit User 1576432 \u003c1576432@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#18: Tryjobs failed"}