Update patch set 1
Patch Set 1:

Jack, if I try to add 
    @implements {FrameAssociated}
annotations to Script or CSSStyleSheetHeaders, typescript complains that 
gen/front_end/sdk/CSSStyleSheetHeader.d.ts(7,88): error TS2749: 'CSSStyleSheetHeader_base' refers to a value, but is being used as a type here. Did you mean 'typeof CSSStyleSheetHeader_base'?
gen/front_end/sdk/Script.d.ts(7,75): error TS2749: 'Script_base' refers to a value, but is being used as a type here. Did you mean 'typeof Script_base'?

Do you know how to work around this?

Patch-set: 1
CC: Gerrit User 1396442 <1396442@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>