Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/dtf_linux_rel](https://cr-buildbucket.appspot.com/build/8736538922259929409) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5868020?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[23/449] ACTION //front_end/panels/freestyler:freestyler(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/freestyler/freestyler-tsconfig.json gen/front_end/panels/freestyler/Cha...(too long)
python3 ../../scripts/build/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/freestyler/freestyler-tsconfig.json

../../front_end/panels/freestyler/FreestylerPanel.ts(372,40): error TS2339: Property 'ABORT' does not exist on type 'typeof ErrorType'.


```
#### [Click here for more information](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8736538866137455105/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 1
Tag: autogenerated:cq:dry-run:1726584226
Attention: {"person_ident":"Gerrit User 1557932 \u003c1557932@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}