Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8794838779683738769) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[125/2159] ACTION //front_end/models/issues_manager:issues_manager-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json

../../front_end/models/issues_manager/FederatedAuthRequestIssue.ts(90,53): error TS2339: Property 'ManifestHttpNotFound' does not exist on type 'typeof FederatedAuthRequestIssueReason'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1670985047
Attention: {"person_ident":"Gerrit User 1541419 \u003c1541419@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}