Update patch set 7
Patch Set 7:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8876717942352965968
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [6/29] ACTION //front_end/sdk:sdk(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/TracingModel.js(233,24): error TS2339: Property 'data' does not exist on type '{ sort_index: number; name: string; snapshot: ObjectSnapshot; }'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8876717574550100768
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [6/29] ACTION //front_end/sdk:sdk(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/TracingModel.js(233,24): error TS2339: Property 'data' does not exist on type '{ sort_index: number; name: string; snapshot: ObjectSnapshot; }'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 7
Tag: autogenerated:cq:dry-run