Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8735948085084936705) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5882525?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[317/1173] ACTION //front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
python3 ../../scripts/build/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/s...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/DebuggerModel.ts(1052,9): error TS2345: Argument of type 'DebugSymbols[] | null' is not assignable to parameter of type 'DebugSymbols | null'.
Property 'type' is missing in type 'DebugSymbols[]' but required in type 'DebugSymbols'.


```
#### [Click here for more information](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8735948085084936705/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 1
Tag: autogenerated:cq:dry-run:1727147505