Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8751730780817347905) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5416374?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1884/2236] ACTION //front_end/models/trace/handlers:unittests(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/trace/handlers/unittests-tsconfig.json gen/front_end/models/trace/handl...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/trace/handlers/unittests-tsconfig.json

../../front_end/models/trace/handlers/PageLoadMetricsHandler.test.ts(275,82): error TS2339: Property 'MarkerName' does not exist on type 'typeof import("/b/s/w/ir/cache/builder/devtools-frontend/out/Debug/gen/front_end/models/trace/handlers/PageLoadMetricsHandler")'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1712096143
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}