Revert "Upgrade ESBuild to 0.15.16"
Build broken for chrome ash.
```
keithlee@keithlee:~/chromium/src$ autoninja -C out_kukui/Release chrome
ninja: Entering directory `out_kukui/Release'
[0/1] Regenerating ninja files
[18721/84314] ACTION //third_party/devtools-frontend-internal/devtools-frontend/front_end/entrypoints/formatter_worker:devtools_entrypoint-formatter_actions-bundle(//build/toolchain/cros:target)
FAILED: gen/third_party/devtools-frontend-internal/devtools-frontend/front_end/entrypoints/formatter_worker/FormatterActions.js
python3 ../../third_party/node/node.py ../../third_party/devtools-frontend-internal/devtools-frontend/scripts/build/esbuild.js gen/third_party/devtools-frontend-internal/devtools-frontend/front_end/entrypoints/formatter_worker/FormatterActions.prebundle.js gen/third_party/devtools-frontend-internal/devtools-frontend/front_end/entrypoints/formatter_worker/FormatterActions.js
Traceback (most recent call last):
  File "/usr/local/google/home/keithlee/chromium/src/out_kukui/Release/../../third_party/node/node.py", line 39, in <module>
    RunNode(sys.argv[1:])
  File "/usr/local/google/home/keithlee/chromium/src/out_kukui/Release/../../third_party/node/node.py", line 34, in RunNode
    raise RuntimeError('Command \'%s\' failed\n%s' % (' '.join(cmd), err))
RuntimeError: Command '/usr/local/google/home/keithlee/chromium/src/out_kukui/Release/../../third_party/node/linux/node-linux-x64/bin/node ../../third_party/devtools-frontend-internal/devtools-frontend/scripts/build/esbuild.js gen/third_party/devtools-frontend-internal/devtools-frontend/front_end/entrypoints/formatter_worker/FormatterActions.prebundle.js gen/third_party/devtools-frontend-internal/devtools-frontend/front_end/entrypoints/formatter_worker/FormatterActions.js' failed
✘ [ERROR] Cannot start service: Host version "0.14.13" does not match binary version "0.15.16"

1 error
failed to run esbuild: Error: The service was stopped
    at /usr/local/google/home/keithlee/chromium/src/third_party/devtools-frontend-internal/devtools-frontend/node_modules/esbuild/lib/main.js:1301:25
    at /usr/local/google/home/keithlee/chromium/src/third_party/devtools-frontend-internal/devtools-frontend/node_modules/esbuild/lib/main.js:637:9
    at Socket.afterClose (/usr/local/google/home/keithlee/chromium/src/third_party/devtools-frontend-internal/devtools-frontend/node_modules/esbuild/lib/main.js:615:7)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

[18904/84314] ACTION //chromeos/assistant/internal:build_libassistant(//build/toolchain/cros:target)
ninja: build stopped: subcommand failed.

```
This reverts commit fc4b4c505539d143bcc9e68cd53d5a51f15cb6f0.

Reason for revert: Breaks chrome ash build

Original change's description:
> Upgrade ESBuild to 0.15.16
>
> Bug: none
> Change-Id: I825c7aa3f351d5741a80652feaf31e1a1cbeb7db
> Reviewed-on: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4061355
> Reviewed-by: Liviu Rau <liviurau@chromium.org>
> Auto-Submit: Jack Franklin <jacktfranklin@chromium.org>
> Commit-Queue: Liviu Rau <liviurau@chromium.org>

Bug: none
Change-Id: I6c6e8c7e7d844482648ffb58bd6a28b7caedee99
No-Presubmit: true
No-Tree-Checks: true
No-Try: true