Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/dtf_linux_rel](https://cr-buildbucket.appspot.com/build/8740085417301049809) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5773061?checksPatchset=2&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[332/972] ACTION //front_end/panels/timeline/components:components(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/timeline/components/components-tsconfig.json gen/front_end/panels/timel...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/t...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/timeline/components/components-tsconfig.json

../../front_end/panels/timeline/components/SidebarAnnotationsTab.ts(83,36): error TS2339: Property 'label' does not exist on type 'Annotation'.
Property 'label' does not exist on type 'EntriesLinkAnnotation'.


```
#### [Click here for more information](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8740085365954372897/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 2
Tag: autogenerated:cq:dry-run:1723202031
Attention: {"person_ident":"Gerrit User 1593257 \u003c1593257@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}