Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> While there are build failures, I don't think they are related to the lack of `@implements` support and are legitimate type errors. Could you take another look at https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket.appspot.com/8887408344365668432/+/steps/compile/0/stdout and resolve these errors?

Regarding ../../front_end/common/AppProvider.js(12,15): error TS2355: A function whose declared type is neither 'void' nor 'any' must return a value.
[gl] So, I think this is definitely related to the lack of @implements support.

../../front_end/common/StringOutputStream.js(11,16): error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).
../../front_end/common/StringOutputStream.js(17,16): error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).
[gl] If I add a type for the 2 @return {!Promise}, I will eventually hit the "error TS2355: A function whose declared type is neither 'void' nor 'any' must return a value." error because these are interface and do not return anything.

Similar scenario regarding Runnable.js. 

I can fix the generic type for the time being and get the patch to hit the "error TS2355: A function whose declared type is neither 'void' nor 'any' must return a value.", which should clear when @implements support is landed.

Patch-set: 2