Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8758099877115681617) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/5224170?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[2069/2179] ACTION //test/unittests/front_end/panels/elements:elements(//build/toolchain/linux:x64)
FAILED: gen/test/unittests/front_end/panels/elements/elements-tsconfig.json gen/test/unittests/front...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/unittests/fro...(too long)

TypeScript compilation failed. Used tsconfig gen/test/unittests/front_end/panels/elements/elements-tsconfig.json

../../test/unittests/front_end/panels/elements/StylePropertyTreeElement_test.ts(661,102): error TS2339: Property 'getReadonly' does not exist on type 'ColorSwatch'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1706022102
Attention: {"person_ident":"Gerrit User 1372423 \u003c1372423@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}