Update patch set 5
Patch Set 5:

Try jobs failed on following builders:
  luci.devtools-frontend.try/devtools_frontend_presubmit JOB_FAILED https://ci.chromium.org/b/8891170510448546688
    There are 3 error(s), 0 warning(s), and 4 notifications(s). Here are the errors:
    
    **ERROR**
    
    ERROR: Found formatting violations.
    
    Ran clang-format on diff
    
    Use git status to check the formatting changes
    
    
    
    **ERROR**
    
    
    
    
    
    **ERROR**
    
    You have changed files that need to be committed.
    
    
    
    To see notifications and warnings, look at the stdout of the presubmit step.
  luci.devtools-frontend.try/devtools_frontend_presubmit JOB_FAILED https://ci.chromium.org/b/8891170321769961616
    There are 3 error(s), 0 warning(s), and 4 notifications(s). Here are the errors:
    
    **ERROR**
    
    ERROR: Found formatting violations.
    
    Ran clang-format on diff
    
    Use git status to check the formatting changes
    
    
    
    **ERROR**
    
    
    
    
    
    **ERROR**
    
    You have changed files that need to be committed.
    
    
    
    To see notifications and warnings, look at the stdout of the presubmit step.

Patch-set: 5
Tag: autogenerated:cq:full-run