Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8757461899135452513) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/5249931?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[614/1088] ACTION //front_end/panels/application:application(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/application/application-tsconfig.json gen/front_end/panels/application/...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/a...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/application/application-tsconfig.json

../../front_end/panels/application/StorageView.ts(199,59): error TS2551: Property 'toKebapCase' does not exist on type 'typeof import("/b/s/w/ir/cache/builder/devtools-frontend/out/Release/gen/front_end/core/platform/string-utilities")'. Did you mean 'toKebabCase'?


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:full-run:1706630366
Attention: {"person_ident":"Gerrit User 1419627 \u003c1419627@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}