Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8772117949128173681) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[3014/4011] ACTION //front_end/panels/sources:sources-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/sources/sources-tsconfig.json gen/front_end/panels/sources/AddSourceMap...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/sources/sources-tsconfig.json

../../front_end/panels/sources/SourcesSearchScope.ts(310,65): error TS2339: Property 'columnNumber' does not exist on type 'SearchMatch'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run:1692653429
Attention: {"person_ident":"Gerrit User 1429955 \u003c1429955@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}