Update patch set 2
Patch Set 2:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8838759922296060640
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [839/1929] ACTION //front_end/models/issues_manager:issues_manager-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json
    
    ../../front_end/models/issues_manager/AttributionReportingIssue.ts(22,83): error TS2366: Function lacks ending return statement and return type does not include 'undefined'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 2
Tag: autogenerated:cv