Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8762436465693195297) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/5095694?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[180/1425] ACTION //front_end/panels/emulation:emulation(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/emulation/emulation-tsconfig.json gen/front_end/panels/emulation/Advanc...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/emulation/emulation-tsconfig.json

../../front_end/panels/emulation/DeviceModeToolbar.ts(425,18): error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1701886411
Attention: {"person_ident":"Gerrit User 1108044 \u003c1108044@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}