Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8780671909972382833) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[912/2353] ACTION //front_end/models/bindings:bindings-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/bindings/bindings-tsconfig.json gen/front_end/models/bindings/Breakpoin...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/b...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/bindings/bindings-tsconfig.json

../../front_end/models/bindings/CompilerScriptMapping.ts(431,76): error TS2454: Variable 'metadata' is used before being assigned.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run:1684495737
Attention: {"person_ident":"Gerrit User 1183894 \u003c1183894@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}