Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Failed Tryjobs:
* [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8750501881416229553). Summary ([view all results](https://chromium-review.googlesource.com/c/5453718?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[735/2235] ACTION //front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/ResourceTreeModel.ts(467,39): error TS2554: Expected 1 arguments, but got 0.


```
#### More information in raw_io.output_text[failure_summary]

---
* [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8750501881416229521). Summary ([view all results](https://chromium-review.googlesource.com/c/5453718?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[35/2323] ACTION //front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/ResourceTreeModel.ts(467,39): error TS2554: Expected 1 arguments, but got 0.


```
#### More information in raw_io.output_text[failure_summary]

---
* [devtools-frontend/try/devtools_frontend_mac_rel](https://cr-buildbucket.appspot.com/build/8750501881416229489). Summary ([view all results](https://chromium-review.googlesource.com/c/5453718?checksPatchset=1&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1133/3593] ACTION //front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/ResourceTreeModel.ts(467,39): error TS2554: Expected 1 arguments, but got 0.


```
#### More information in raw_io.output_text[failure_summary]

---
* [devtools-frontend/try/dtf_presubmit_win64](https://cr-buildbucket.appspot.com/build/8750501881416229441). Summary ([view all results](https://chromium-review.googlesource.com/c/5453718?checksPatchset=1&tab=checks)):

---
There are 2 errors, 1 warning, and 19 notifications.

Here are the errors:

**ERROR**

You have changed files that need to be committed:

Presubmit result call stack is:

  File "C:\\b\\s\\w\\ir\\kitchen\-checkout\\depot\_tools\\presubmit\_support\.py", line 1806, in \_execute\_with\_local\_working\_directory

    self\.\_run\_check\_function\(function\_name, context,

  File "C:\\b\\s\\w\\ir\\kitchen\-checkout\\depot\_tools\\presubmit\_support\.py", line 1837, in \_run\_check\_function

**Error size > 450 chars, there are 12 more error(s) (18 total)**

**The complete output can be found at the bottom of the presubmit stdout.**

To see notifications and warnings, look at the stdout of the presubmit step.

---

Patch-set: 1
Tag: autogenerated:cq:full-run:1713268117
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}