Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/dtf_linux_rel](https://cr-buildbucket.appspot.com/build/8742332267587521473) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5708011?checksPatchset=2&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[116/680] ACTION //test/interactions/panels/performance/timeline:timeline(//build/toolchain/linux:x64)
FAILED: gen/test/interactions/panels/performance/timeline/timeline-tsconfig.json gen/test/interactio...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/interactions/...(too long)

TypeScript compilation failed. Used tsconfig gen/test/interactions/panels/performance/timeline/timeline-tsconfig.json

../../test/interactions/panels/performance/timeline/timeline_selection_test.ts(257,73): error TS2339: Property 'innerText' does not exist on type 'Element'.


```
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8742332210352921713/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 2
Tag: autogenerated:cq:dry-run:1721059262
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}