Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8785838982903789073) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[29/2355] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json

../../front_end/core/sdk/CSSRule.ts(115,37): error TS2339: Property 'nestingSelectors' does not exist on type 'CSSRule'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:full-run:1679568018
Attention: {"person_ident":"Gerrit User 1541419 \u003c1541419@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}