Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8825701162878512481
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [891/2012] ACTION //front_end/ui/legacy:ui-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/ui/legacy/ui-tsconfig.json gen/front_end/ui/legacy/ARIAUtils.js gen/front_end/...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/legac...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/ui/legacy/ui-tsconfig.json
    
    ../../front_end/ui/legacy/Treeoutline.ts(403,11): error TS2339: Property 'appendStyle' does not exist on type 'typeof import("/b/s/w/ir/cache/builder/devtools-frontend/out/Debug/gen/front_end/ui/legacy/utils/utils")'.
    
    
    ```
    #### More information in raw_io.output_text[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8825700953159183985
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [891/2012] ACTION //front_end/ui/legacy:ui-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/ui/legacy/ui-tsconfig.json gen/front_end/ui/legacy/ARIAUtils.js gen/front_end/...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/legac...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/ui/legacy/ui-tsconfig.json
    
    ../../front_end/ui/legacy/Treeoutline.ts(403,11): error TS2339: Property 'appendStyle' does not exist on type 'typeof import("/b/s/w/ir/cache/builder/devtools-frontend/out/Debug/gen/front_end/ui/legacy/utils/utils")'.
    
    
    ```
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1189020 \u003c1189020@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: CQ dry run failed."}