Update patch set 17
Patch Set 17:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8747139891932986017) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5551153?checksPatchset=17&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[3/908] ACTION //front_end/models/issues_manager:issues_manager(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json

../../front_end/models/issues_manager/CookieDeprecationMetadataIssue.ts(28,110): error TS2339: Property 'operation' does not exist on type 'CookieDeprecationMetadataIssueDetails'.
```
##### ...The message was too long...
#### More information in [failure_summary](https://logs.chromium.org/logs/devtools-frontend/buildbucket/cr-buildbucket/8747139891932986017/+/u/compile/raw_io.output_text_failure_summary_)

Patch-set: 17
Tag: autogenerated:cq:dry-run:1716474269
Attention: {"person_ident":"Gerrit User 1579342 \u003c1579342@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#17: Tryjobs failed"}