Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_win64_rel](https://cr-buildbucket.appspot.com/build/8792163830428606081) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[379/532] ACTION //test/unittests/front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/test/unittests/front_end/core/sdk/sdk-tsconfig.json gen/test/unittests/front_end/core/sd...(too long)
C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)

TypeScript compilation failed. Used tsconfig gen/test/unittests/front_end/core/sdk/sdk-tsconfig.json

../../test/unittests/front_end/core/sdk/Cookie_test.ts(61,31): error TS2339: Property 'sameParty' does not exist on type 'Cookie'.
../../test/unittests/front_end/core/sdk/Cookie_test.ts(100,31): error TS2339: Property 'sameParty' does not exist on type 'Cookie'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run:1673536187
Attention: {"person_ident":"Gerrit User 1467227 \u003c1467227@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}