Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_dbg](https://cr-buildbucket.appspot.com/build/8763539203905584481) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/5054334?checksPatchset=2&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[1969/2159] ACTION //test/unittests/front_end/core/sdk:sdk(//build/toolchain/linux:x64)
FAILED: gen/test/unittests/front_end/core/sdk/sdk-tsconfig.json gen/test/unittests/front_end/core/sd...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/unittests/fro...(too long)

TypeScript compilation failed. Used tsconfig gen/test/unittests/front_end/core/sdk/sdk-tsconfig.json

../../test/unittests/front_end/core/sdk/AutofillModel_test.ts(22,44): error TS2339: Property 'agent' does not exist on type 'AutofillModel'.
../../test/unittests/front_end/core/sdk/AutofillModel_test.ts(23,47): error TS2339: Property 'agent' does not exist on type 'AutofillModel'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run:1700834757
Attention: {"person_ident":"Gerrit User 1396454 \u003c1396454@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}