Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8771167253584155617) has failed with summary:

---
#### Step _compile_ failed. Error logs are shown below:
```
[10/490] ACTION //front_end/panels/application/components:components-typescript(//build/toolchain/linux:x64)
FAILED: gen/front_end/panels/application/components/components-tsconfig.json gen/front_end/panels/ap...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/panels/a...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/panels/application/components/components-tsconfig.json

../../front_end/panels/application/components/FrameDetailsView.ts(278,10): error TS2339: Property '#prerenderedUrl' does not exist on type 'FrameDetailsReportView'.
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 2
Tag: autogenerated:cq:dry-run:1693559999
Attention: {"person_ident":"Gerrit User 1597023 \u003c1597023@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}