Update patch set 11
Patch Set 11:

Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8854560955268148128
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [66/2110] ACTION //front_end/ui:ui-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/ui/ui-tsconfig.json gen/front_end/ui/ui-tsconfig.json.tsbuildinfo gen/front_en...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/ui-tsc...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/ui/ui-tsconfig.json
    
    ../../front_end/ui/SplitWidget.js(1000,64): error TS2339: Property '_showHideSidebarButtonTitle' does not exist on type 'SplitWidget'.
    ../../front_end/ui/SplitWidget.js(1001,64): error TS2339: Property '_showHideSidebarButtonTitle' does not exist on type 'SplitWidget'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8854560829823904896
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [34/2045] ACTION //front_end/ui:ui-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/ui/ui-tsconfig.json gen/front_end/ui/ui-tsconfig.json.tsbuildinfo gen/front_en...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/ui-tsc...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/ui/ui-tsconfig.json
    
    ../../front_end/ui/SplitWidget.js(1000,64): error TS2339: Property '_showHideSidebarButtonTitle' does not exist on type 'SplitWidget'.
    ../../front_end/ui/SplitWidget.js(1001,64): error TS2339: Property '_showHideSidebarButtonTitle' does not exist on type 'SplitWidget'.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 11
Tag: autogenerated:cq:full-run