Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8765549536381111553) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/4994679?checksPatchset=1&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[529/572] ACTION //test/unittests/front_end/panels/timeline:timeline(//build/toolchain/linux:x64)
FAILED: gen/test/unittests/front_end/panels/timeline/timeline-tsconfig.json gen/test/unittests/front...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/unittests/fro...(too long)

TypeScript compilation failed. Used tsconfig gen/test/unittests/front_end/panels/timeline/timeline-tsconfig.json

../../test/unittests/front_end/panels/timeline/SourceMapsResolver_test.ts(65,13): error TS2739: Type '{ codeType: string; functionName: string; scriptId: number; }' is missing the following properties from type 'TraceEventCallFrame': columnNumber, lineNumber, url
```
##### ...The message was too long...
#### More information in raw_io.output_text[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run:1698917552
Attention: {"person_ident":"Gerrit User 1447167 \u003c1447167@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}