Update patch set 4
Patch Set 4:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_linux_rel](https://cr-buildbucket.appspot.com/build/8750304961390225521) has failed with summary ([view all results](https://chromium-review.googlesource.com/c/5448512?checksPatchset=4&tab=checks)):

---
#### Step _compile_ failed. Error logs are shown below:
```
[57/2081] ACTION //front_end/models/issues_manager:issues_manager(//build/toolchain/linux:x64)
FAILED: gen/front_end/models/issues_manager/issues_manager-tsconfig.json gen/front_end/models/issues...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/i...(too long)

TypeScript compilation failed. Used tsconfig gen/front_end/models/issues_manager/issues_manager-tsconfig.json

../../front_end/models/issues_manager/CookieIssue.ts(273,70): error TS1361: 'FrontendMessageSource' cannot be used as a value because it was imported using 'import type'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 4
Tag: autogenerated:cq:dry-run:1713455848
Attention: {"person_ident":"Gerrit User 1434270 \u003c1434270@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#4: Tryjobs failed"}