Update patch set 3
Patch Set 3:

This CL has failed the run. Reason:

Tryjob [devtools-frontend/try/devtools_frontend_mac_rel](https://cr-buildbucket.appspot.com/build/8758790151348679585) has failed with summary [(view all results)](https://chromium-review.googlesource.com/c/5194786?checksPatchset=3&tab=checks):

---
#### Step _compile_ failed. Error logs are shown below:
```
[3367/3523] ACTION //test/unittests/front_end/models/trace/handlers:handlers(//build/toolchain/linux:x64)
FAILED: gen/test/unittests/front_end/models/trace/handlers/handlers-tsconfig.json gen/test/unittests...(too long)
python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/test/unittests/fro...(too long)

TypeScript compilation failed. Used tsconfig gen/test/unittests/front_end/models/trace/handlers/handlers-tsconfig.json

../../test/unittests/front_end/models/trace/handlers/ScreenshotsHandler_test.ts(66,100): error TS2339: Property 'origArgs' does not exist on type 'TraceEventArgs & { dataUri: string; }'.


```
#### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run:1705363802
Attention: {"person_ident":"Gerrit User 1118499 \u003c1118499@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: Tryjobs failed"}