Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8863096578234531392
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [5/1729] ACTION //front_end/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/CPUProfileDataModel.js(280,7): error TS2740: Type 'Float64Array' is missing the following properties from type 'number[]': pop, push, concat, shift, and 12 more.
    
    
    ```
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8863096431388415024
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1/1725] ACTION //front_end/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/CPUProfileDataModel.js(280,7): error TS2740: Type 'Float64Array' is missing the following properties from type 'number[]': pop, push, concat, shift, and 12 more.
    
    
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run