Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8856117090241367472
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [3/2573] ACTION //front_end/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/NetworkRequest.js(1755,47): error TS2339: Property 'SamePartyFromCrossPartyContext' does not exist on type 'typeof CookieBlockedReason'.
    ../../front_end/sdk/NetworkRequest.js(1805,50): error TS2339: Property 'SamePartyFromCrossPartyContext' does not exist on type 'typeof SetCookieBlockedReason'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8856116964804038704
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [29/2600] ACTION //front_end/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/sdk/sdk-tsconfig.json gen/front_end/sdk/sdk-tsconfig.json.tsbuildinfo gen/fron...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/sdk/sdk-t...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/sdk/sdk-tsconfig.json
    
    ../../front_end/sdk/NetworkRequest.js(1755,47): error TS2339: Property 'SamePartyFromCrossPartyContext' does not exist on type 'typeof CookieBlockedReason'.
    ../../front_end/sdk/NetworkRequest.js(1805,50): error TS2339: Property 'SamePartyFromCrossPartyContext' does not exist on type 'typeof SetCookieBlockedReason'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run