Copy requests as Python in the Network tab
This is a work in progress (/ a feature request in the form of a half
finished patch). I was unable to set up the development environment.
Here's roughly what I did (Ubuntu 20.10):

sudo apt install ninja-build clang

git clone https://gn.googlesource.com/gn
cd gn
python3 build/gen.py
ninja -C out
out/gn_unittests
cd ..

git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git


sudo apt install python2
sudo apt install python-is-python3
curl https://raw.githubusercontent.com/pypa/get-pip/master/2.7/get-pip.py -o get-pip.py
sudo python2.7 get-pip.py
sudo python2.7 -m pip install virtualenv

mkdir devtools
cd devtools
fetch devtools-frontend
cd devtools-frontend
gn gen out/Default
autoninja -C out/Default

The error I get on the last step:

[E2021-02-05T19:14:45.275742-05:00 27746 0 annotate.go:241] original error: no such tag
[E2021-02-05T19:14:45.275794-05:00 27746 0 annotate.go:241]
[E2021-02-05T19:14:45.275815-05:00 27746 0 annotate.go:241] goroutine 30:
[E2021-02-05T19:14:45.275838-05:00 27746 0 annotate.go:241] #0 go.chromium.org/luci/cipd/client/cipd/client.go:1838 - cipd.(*clientImpl).humanErr()
[E2021-02-05T19:14:45.275858-05:00 27746 0 annotate.go:241] #1 go.chromium.org/luci/cipd/client/cipd/client.go:816 - cipd.(*clientImpl).ResolveVersion()
[E2021-02-05T19:14:45.275877-05:00 27746 0 annotate.go:241] #2 go.chromium.org/luci/cipd/client/cipd/resolver.go:176 - cipd.(*Resolver).resolveVersion.func1()
[E2021-02-05T19:14:45.275896-05:00 27746 0 annotate.go:241] #3 go.chromium.org/luci/common/sync/promise/promise.go:84 - promise.(*Promise).runGen()
[E2021-02-05T19:14:45.275913-05:00 27746 0 annotate.go:241] #4 runtime/asm_amd64.s:1374 - runtime.goexit()
[E2021-02-05T19:14:45.275932-05:00 27746 0 annotate.go:241]
[E2021-02-05T19:14:45.275947-05:00 27746 0 annotate.go:241] goroutine 29:
[E2021-02-05T19:14:45.275962-05:00 27746 0 annotate.go:241] From frame 0 to 0, the following wrappers were found:
[E2021-02-05T19:14:45.275980-05:00 27746 0 annotate.go:241]   internal reason: MultiError 1/1: following first non-nil error.
[E2021-02-05T19:14:45.275998-05:00 27746 0 annotate.go:241]
[E2021-02-05T19:14:45.276014-05:00 27746 0 annotate.go:241] #0 go.chromium.org/luci/cipd/client/cipd/ensure/file.go:255 - ensure.(*File).Resolve.func1.1()
[E2021-02-05T19:14:45.276032-05:00 27746 0 annotate.go:241]   reason: failed to resolve infra/python/wheels/psutil/linux-amd64_cp38_cp38@version:5.6.2 (line 0)
[E2021-02-05T19:14:45.276050-05:00 27746 0 annotate.go:241]
[E2021-02-05T19:14:45.276066-05:00 27746 0 annotate.go:241] #1 go.chromium.org/luci/common/sync/parallel/runner.go:51 - parallel.(*WorkItem).execute()
[E2021-02-05T19:14:45.276084-05:00 27746 0 annotate.go:241] #2 go.chromium.org/luci/common/sync/parallel/runner.go:149 - parallel.(*Runner).dispatchLoopBody.func2()
[E2021-02-05T19:14:45.276102-05:00 27746 0 annotate.go:241] #3 runtime/asm_amd64.s:1374 - runtime.goexit()
[E2021-02-05T19:14:45.276119-05:00 27746 0 annotate.go:241]
[E2021-02-05T19:14:45.276135-05:00 27746 0 annotate.go:241] goroutine 1:
[E2021-02-05T19:14:45.276152-05:00 27746 0 annotate.go:241] #0 go.chromium.org/luci/vpython/venv/config.go:183 - venv.(*Config).makeEnv()
[E2021-02-05T19:14:45.276170-05:00 27746 0 annotate.go:241]   reason: failed to resolve packages
[E2021-02-05T19:14:45.276208-05:00 27746 0 annotate.go:241]
[E2021-02-05T19:14:45.276226-05:00 27746 0 annotate.go:241] #1 go.chromium.org/luci/vpython/venv/venv.go:163 - venv.With()
[E2021-02-05T19:14:45.276243-05:00 27746 0 annotate.go:241] #2 go.chromium.org/luci/vpython/run.go:62 - vpython.Run()
[E2021-02-05T19:14:45.276270-05:00 27746 0 annotate.go:241] #3 go.chromium.org/luci/vpython/application/application.go:320 - application.(*application).mainImpl()
[E2021-02-05T19:14:45.276289-05:00 27746 0 annotate.go:241] #4 go.chromium.org/luci/vpython/application/application.go:408 - application.(*Config).Main.func1()
[E2021-02-05T19:14:45.276306-05:00 27746 0 annotate.go:241] #5 go.chromium.org/luci/vpython/application/support.go:46 - application.run()
[E2021-02-05T19:14:45.276325-05:00 27746 0 annotate.go:241] #6 go.chromium.org/luci/vpython/application/application.go:407 - application.(*Config).Main()
[E2021-02-05T19:14:45.276342-05:00 27746 0 annotate.go:241] #7 vpython/main.go:109 - main.mainImpl()
[E2021-02-05T19:14:45.276359-05:00 27746 0 annotate.go:241] #8 vpython/main.go:115 - main.main()
[E2021-02-05T19:14:45.276376-05:00 27746 0 annotate.go:241] #9 runtime/proc.go:204 - runtime.main()
[E2021-02-05T19:14:45.276393-05:00 27746 0 annotate.go:241] #10 runtime/asm_amd64.s:1374 - runtime.goexit()

I also got this error first, but it went away

[E2021-02-05T18:42:32.678676-05:00 19680 0 venv.go:975] Command (cwd=/tmp/vpython_bootstrap804048449/packages/virtualenv-15.1.0): [/usr/bin/python -B -E -s virtualenv.py --no-download /home/brs/.vpython-root/05e068]
Process output:
Traceback (most recent call last):
  File "virtualenv.py", line 25, in <module>
    import distutils.sysconfig
ModuleNotFoundError: No module named 'distutils.sysconfig'

Please give me some pointers. Should I try to change to an
older Ubuntu that still uses Python 2?

Or feel free to finish this, there is a project that converts
the result of "copy as cURL" to Python,
https://github.com/NickCarneiro/curlconverter/
It has a lot of users even though it doesn't always work (for
example it breaks if the output uses bash ASCII strings). I
use it regularly and it's tedious to copy in the Network tab,
paste that to https://curl.trillworks.com/ and copy the result.


Change-Id: Id78564ea4353f13703ae2f1cebf305fbea8cf448