Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_win64_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8801858734261819105
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [63/1174] ACTION //front_end/models/extensions:extensions-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/models/extensions/extensions-tsconfig.json gen/front_end/models/extensions/Ext...(too long)
    C:/b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.exe ../../third_party/typescript/ts_library.py --...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/models/extensions/extensions-tsconfig.json
    
    ../../front_end/models/extensions/ExtensionAPI.ts(1212,87): error TS2339: Property 'allowFileAccess' does not exist on type 'ExtensionDescriptor'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 3
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1511722 \u003c1511722@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#3: CQ dry run failed."}