Update patch set 1
Patch Set 1:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8844457309361731136
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1065/1730] ACTION //front_end/models/extensions:extensions-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/models/extensions/extensions-tsconfig.json gen/front_end/models/extensions/Ext...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/models/e...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/models/extensions/extensions-tsconfig.json
    
    ../../front_end/models/extensions/ExtensionServer.ts(496,47): error TS2531: Object is possibly 'null'.
    ../../front_end/models/extensions/ExtensionServer.ts(513,25): error TS2339: Property '_requestId' does not exist on type 'EntryDTO'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 1
Tag: autogenerated:cq:dry-run