Update patch set 6
Patch Set 6:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_blink_light_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8810020215698808305
    #### Step _compile (with patch)_ failed. Error logs are shown below:
    ```
    [186/12455] ACTION //third_party/devtools-frontend/src/front_end/core/sdk:sdk-typescript(//build/toolchain/linux:clang_x64)
    FAILED: gen/third_party/devtools-frontend/src/front_end/core/sdk/sdk-tsconfig.json gen/third_party/d...(too long)
    python3 ../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py --tsconfig_outp...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/third_party/devtools-frontend/src/front_end/core/sdk/sdk-tsconfig.json
    
    ../../third_party/devtools-frontend/src/front_end/core/sdk/CSSScope.ts(27,28): error TS2339: Property 'active' does not exist on type 'CSSScope'.
    
    
    ```
    #### More information in raw_io.output_text[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8810020215698808273
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [758/2099] ACTION //front_end/core/sdk:sdk-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/core/sdk/sdk-tsconfig.json gen/front_end/core/sdk/AccessibilityModel.js gen/fr...(too long)
    python3 ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/core/sdk...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/core/sdk/sdk-tsconfig.json
    
    ../../front_end/core/sdk/CSSScope.ts(27,28): error TS2339: Property 'active' does not exist on type 'CSSScope'.
    
    
    ```
    #### More information in raw_io.output_text[failure_summary]

Patch-set: 6
Tag: autogenerated:cq:dry-run
Attention: {"person_ident":"Gerrit User 1524702 \u003c1524702@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"ps#6: CQ dry run failed."}