Update patch set 5
Patch Set 5:

Dry run: Failed builds:
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8858293083548272576
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1062/4038] ACTION //front_end/ui:ui-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/ui/ui-tsconfig.json gen/front_end/ui/ui-tsconfig.json.tsbuildinfo gen/front_en...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/ui-tsc...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/ui/ui-tsconfig.json
    
    ../../front_end/ui/SearchableView.js(401,9): error TS2367: This condition will always return 'false' since the types 'boolean' and 'string' have no overlap.
    ../../front_end/ui/SearchableView.js(416,15): error TS2339: Property 'key' does not exist on type 'Event'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]
  luci.devtools-frontend.try/devtools_frontend_linux_dbg JOB_FAILED https://cr-buildbucket.appspot.com/build/8858292852880106784
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [1063/4038] ACTION //front_end/ui:ui-typescript(//build/toolchain/linux:x64)
    FAILED: gen/front_end/ui/ui-tsconfig.json gen/front_end/ui/ui-tsconfig.json.tsbuildinfo gen/front_en...(too long)
    python ../../third_party/typescript/ts_library.py --tsconfig_output_location gen/front_end/ui/ui-tsc...(too long)
    
    TypeScript compilation failed. Used tsconfig gen/front_end/ui/ui-tsconfig.json
    
    ../../front_end/ui/SearchableView.js(401,9): error TS2367: This condition will always return 'false' since the types 'boolean' and 'string' have no overlap.
    ../../front_end/ui/SearchableView.js(416,15): error TS2339: Property 'key' does not exist on type 'Event'.
    ```
    ##### ...The message was too long...
    #### More information in raw_io.output[failure_summary]

Patch-set: 5
Tag: autogenerated:cq:dry-run